"""Page endpoints — the serving tier's read path (stage 5, TRD §08).

One resolution, then one select per section. Not a wide join: a section
that failed to promote returns no row, which is a different fact from a
section that promoted empty, and a join would flatten the two into the
same nulls. Nothing here recomputes a score, delta, share or age — every
one of those is either promoted or generated by the database.
"""
from __future__ import annotations

from .computed import apply as computed_apply
from .redaction import page_forbidden, redact_section
from .serving_spec import page_sections, readers, assemble
from .value_chain import serve_value_chain

AUDIENCES = ("internal", "customer")


class ApiError(Exception):
    def __init__(self, status: int, code: str, detail: str):
        super().__init__(detail)
        self.status, self.code, self.detail = status, code, detail


def _rows(cur, table: str, run_id) -> list[dict]:
    cur.execute(f"SELECT * FROM {table} WHERE run_id = %s", (run_id,))
    cols = [d[0] for d in cur.description]
    return [dict(zip(cols, r)) for r in cur.fetchall()]


def resolve_run(cur, display_id: str, run: str | None, allow_history: bool):
    """The entity and the run to serve, read from the ONE materialised view
    svc_api is granted (0013). Not the base tables: svc_api holds no SELECT
    on entities or runs by design, and resolving the active run in two
    places is how a header and its rows come to disagree."""
    cur.execute("""SELECT entity_id, display_id, legal_name, sub_vertical, size_tier,
                          run_id, request_id, run_seq, is_active, run_status,
                          composite, scored_cells, catalogue_cells,
                          ccg_catalog_version, completed_at, promoted_at,
                          assessment_date, assessment_date_basis,
                          assessment_date_source, refresh_due_date
                     FROM serving_directory
                    WHERE display_id = %s
                    -- NULLS LAST is load-bearing: `is_active` is a nullable
                    -- boolean, and PostgreSQL sorts NULL FIRST under DESC. A
                    -- promoted run that never had the column set would
                    -- therefore sort AHEAD of the active one, and this
                    -- function would 404 an entity that is serving.
                    ORDER BY is_active DESC NULLS LAST, promoted_at DESC""",
                (display_id,))
    rows = cur.fetchall()
    if not rows:
        # No promoted run for this entity — including an entity that exists
        # but has never promoted, which is the same fact to a reader.
        raise ApiError(404, "entity_not_found",
                       f"no promoted run for {display_id!r}")
    if run:
        picked = next((r for r in rows if str(r[5]) == str(run)), None)
        if picked is None:
            raise ApiError(404, "entity_not_found",
                           f"run {run} has no promoted rows under {display_id}")
        if not picked[8] and not allow_history:
            raise ApiError(409, "run_superseded",
                           "the pinned run is no longer active; pass "
                           "history=true to read it deliberately")
    else:
        picked = rows[0]
        if not picked[8]:
            raise ApiError(404, "entity_not_found",
                           f"{display_id} has no active promoted run")

    entity = {"display_id": picked[1], "entity_name": picked[2],
              "sub_vertical": picked[3], "size_tier": picked[4]}
    run_meta = {"run_id": str(picked[5]), "request_id": picked[6],
                "run_seq": picked[7],
                "completed_at": picked[14].isoformat() if picked[14] else None,
                "promoted_at": picked[15].isoformat() if picked[15] else None,
                "ccg_catalog_version": picked[13], "scored_cells": picked[11],
                "catalogue_cells": picked[12], "status": picked[9],
                "is_active": bool(picked[8]),
                "composite": float(picked[10]) if picked[10] is not None else None,
                # The assessment date and the rung it came from travel with
                # every run this function resolves, so a page header cannot
                # render a date whose provenance the cadence block contradicts
                # (0031). `completed_at` above is retained: it is what the
                # ingest wrote, and the two agreeing is a fact worth being
                # able to check rather than one to assume.
                "assessment_date": (picked[16].isoformat()
                                    if hasattr(picked[16], "isoformat")
                                    else picked[16]),
                "assessment_date_basis": picked[17],
                "assessment_date_source": picked[18],
                "refresh_due_date": (picked[19].isoformat()
                                     if hasattr(picked[19], "isoformat")
                                     else picked[19])}
    return picked[0], entity, run_meta, picked[15]


# Bump this string whenever a SERVING RULE changes — redaction, a
# computed-at-read field, a band or thinness derivation, anything that
# changes the bytes for a run that has not been re-promoted.
#
# Why it has to exist: the tag was run_id.promoted_epoch.audience, and none
# of those three move when a serving rule is fixed. So every cached client
# would have gone on holding the defective body — including the customer body
# carrying the vendor pitch that the redaction fix removes — and the fix would
# have been invisible to exactly the readers it was for. `subverticals.py`
# already carries SCOPE_TAG for this reason; this is the same lesson at the
# page grain.
#
#   @1  the shape as it shipped
#   @2  2026-08-09 — redaction walker performs its strips; r_layer stripped
#       by key; vendor-name safety net; audience default-deny
#   @3  2026-08-09 — migration 0043 moved 30,269 duplicated re-mint links
#       and recomputed linked_evidence_count on 29,622 cells corpus-wide.
#       serving_subcaps is a live view over those counts, so the served
#       thin flags changed under an unmoved promoted_at — without this
#       bump every cached client 304s onto the inflated counts.
SERVE_RULES = "serve-rules@3"


def etag_for(run_meta: dict, audience: str) -> str:
    """W/"<run_id>.<promoted_at epoch>.<audience>.<serve-rules>" — the
    audience is part of the tag because one run serves two different
    documents (TRD §19), and the serving-rule tag is part of it because the
    same run also serves different documents before and after a rule
    change."""
    promoted = run_meta.get("promoted_at") or ""
    epoch = "0"
    if promoted:
        from datetime import datetime
        try:
            epoch = str(int(datetime.fromisoformat(promoted).timestamp()))
        except ValueError:
            epoch = "0"
    return f'W/"{run_meta["run_id"]}.{epoch}.{audience}.{SERVE_RULES}"'


def build_page(cur, page: str, display_id: str, audience: str = "internal",
               run: str | None = None, role: str | None = None,
               allow_history: bool = False) -> dict:
    if audience not in AUDIENCES:
        raise ApiError(400, "unknown_audience",
                       f"audience must be one of {' · '.join(AUDIENCES)}")
    sections = page_sections(page)
    if not sections:
        raise ApiError(404, "unknown_page", f"no page {page!r}")
    forbidden = page_forbidden(page, audience, role)
    if forbidden:
        raise ApiError(403, "audience_forbidden", forbidden)

    entity_id, entity, run_meta, _ = resolve_run(cur, display_id, run, allow_history)

    out_sections = {}
    for section in sections:
        r = readers()[(page, section)]
        if r["grain"] == "none":
            # The evidence store is not a per-run serving table: promote
            # writes no rows for it (its writer grain is "none") and it is
            # keyed by evidence id, not run. Saying so is honest; querying
            # it by run_id would be a column that does not exist. The
            # store is read through the evidence drawer, per id.
            out_sections[section] = {
                "data": None, "data_source": "external",
                "provenance": None, "produced_at": None,
                "producer_version": None, "e_ids": [],
                "empty_state": {
                    "kind": "served_from_evidence_store",
                    "reason": ("this section's rows live in the run's evidence "
                               "store and are read by evidence id rather than "
                               "by page"),
                    "sources_searched": []},
            }
            continue
        rows = _rows(cur, r["table"], run_meta["run_id"])
        built = assemble(page, section, rows)
        if page == "heatmap" and section == "value_chain":
            # H9 is SERVER-DERIVED: its contract is `fields: {}` and the
            # Backend Schema derives it by joining ccg_value_chains to
            # ccg_vc_mapping against the run's served cells. The promoted
            # row contributes only its envelope (the normal promote writes
            # envelope-only for this section); the arrangement is computed
            # here whether or not that row exists, and the empty state
            # names what was searched when the catalogue has none.
            out_sections[section] = serve_value_chain(
                cur, entity, run_meta, built, audience)
            continue
        if built is None:
            # A section with no serving row did not promote. Reported as an
            # explicit state rather than an empty object: blank and broken
            # must not look the same (TRD §08).
            out_sections[section] = {
                "data": None, "data_source": "empty", "provenance": None,
                "produced_at": None, "producer_version": None, "e_ids": [],
                "empty_state": {"kind": "section_not_promoted",
                                "reason": "no serving row for this run",
                                "sources_searched": []},
            }
            continue

        env, stamps = built["env"], built["stamps"]
        # Computed-at-read BEFORE redaction, so a census count is subject to
        # the same audience rules as a promoted one — and so a field the
        # contract calls computed is never served as the producer's copy of
        # a number the app was supposed to derive (invariant 8).
        computed_apply(cur, page, section, built["data"], run_meta, entity_id)
        data, report = redact_section(page, section, built["data"],
                                      env.get("internal_only"), audience)
        if data is None:
            out_sections[section] = {
                "data": None, "data_source": "withheld", "provenance": None,
                "produced_at": None, "producer_version": None, "e_ids": [],
                "empty_state": {"kind": "withheld_for_audience",
                                "reason": "this surface is not served to the "
                                          "customer audience",
                                "sources_searched": []},
            }
            continue

        empty = env.get("empty_state")
        out_sections[section] = {
            "data": data,
            "data_source": "empty" if empty else "producer",
            "provenance": stamps.get("provenance"),
            "produced_at": (stamps.get("promoted_at").isoformat()
                            if hasattr(stamps.get("promoted_at"), "isoformat")
                            else stamps.get("promoted_at")),
            "producer_version": stamps.get("producer_version"),
            "e_ids": env.get("e_ids") or [],
            "empty_state": empty,
        }
        removed = (len(report["paths_stripped"]) + len(report["keys_stripped"])
                   + len(report["vendor_named"]))
        if audience == "customer" and removed:
            # A COUNT, not the paths. The receipt exists so a reader can tell
            # blank-because-withheld from blank-because-empty, and for that
            # the number is enough. The path strings are not: they carry the
            # field names, and `platform_story.platforms[0].zennify_pathway`
            # names the assessing vendor five times in a client's own body —
            # the leak this redaction pass exists to close, re-opened by its
            # own receipt. Measured in production after the first fix: the
            # only five occurrences left were in this list.
            out_sections[section]["redacted_count"] = removed
            out_sections[section]["redaction_note"] = (
                "fields on this surface are held for the internal audience")

    return {"entity": entity, "run": run_meta, "audience": audience,
            "page": page, "sections": out_sections}
