"""Page endpoints — the serving tier's read path (stage 5, TRD §08).

One resolution, then one select per section. Not a wide join: a section
that failed to promote returns no row, which is a different fact from a
section that promoted empty, and a join would flatten the two into the
same nulls. Nothing here recomputes a score, delta, share or age — every
one of those is either promoted or generated by the database.
"""
from __future__ import annotations

from .redaction import page_forbidden, redact_section
from .serving_spec import page_sections, readers, assemble

AUDIENCES = ("internal", "customer")


class ApiError(Exception):
    def __init__(self, status: int, code: str, detail: str):
        super().__init__(detail)
        self.status, self.code, self.detail = status, code, detail


def _rows(cur, table: str, run_id) -> list[dict]:
    cur.execute(f"SELECT * FROM {table} WHERE run_id = %s", (run_id,))
    cols = [d[0] for d in cur.description]
    return [dict(zip(cols, r)) for r in cur.fetchall()]


def resolve_run(cur, display_id: str, run: str | None, allow_history: bool):
    """The entity and the run to serve: the pinned run when asked for, else
    the active promoted one."""
    cur.execute("""SELECT id, display_id, legal_name, sub_vertical, size_tier
                     FROM entities WHERE display_id = %s""", (display_id,))
    ent = cur.fetchone()
    if ent is None:
        raise ApiError(404, "entity_not_found", f"no entity {display_id!r}")
    entity_id = ent[0]

    if run:
        cur.execute("""SELECT id, request_id, completed_at, promoted_at,
                              ccg_catalog_version, scored_cells, catalogue_cells,
                              status, composite
                         FROM runs WHERE id = %s AND entity_id = %s""",
                    (run, entity_id))
        row = cur.fetchone()
        if row is None:
            raise ApiError(404, "entity_not_found",
                           f"run {run} does not belong to {display_id}")
        if row[7] != "ACTIVE" and not allow_history:
            raise ApiError(409, "run_superseded",
                           "the pinned run is no longer active; pass "
                           "history=true to read it deliberately")
    else:
        cur.execute("""SELECT id, request_id, completed_at, promoted_at,
                              ccg_catalog_version, scored_cells, catalogue_cells,
                              status, composite
                         FROM runs
                        WHERE entity_id = %s AND status = 'ACTIVE'
                          AND promoted_at IS NOT NULL
                        ORDER BY promoted_at DESC LIMIT 1""", (entity_id,))
        row = cur.fetchone()
        if row is None:
            raise ApiError(404, "entity_not_found",
                           f"{display_id} has no promoted run")

    entity = {"display_id": ent[1], "entity_name": ent[2],
              "sub_vertical": ent[3], "size_tier": ent[4]}
    run_meta = {"run_id": str(row[0]), "request_id": row[1],
                "completed_at": row[2].isoformat() if row[2] else None,
                "promoted_at": row[3].isoformat() if row[3] else None,
                "ccg_catalog_version": row[4], "scored_cells": row[5],
                "catalogue_cells": row[6], "is_active": row[7] == "ACTIVE",
                "composite": float(row[8]) if row[8] is not None else None}
    return entity_id, entity, run_meta, row[3]


def etag_for(run_meta: dict, audience: str) -> str:
    """W/"<run_id>.<promoted_at epoch>.<audience>" — the audience is part of
    the tag because one run serves two different documents (TRD §19)."""
    promoted = run_meta.get("promoted_at") or ""
    epoch = "0"
    if promoted:
        from datetime import datetime
        try:
            epoch = str(int(datetime.fromisoformat(promoted).timestamp()))
        except ValueError:
            epoch = "0"
    return f'W/"{run_meta["run_id"]}.{epoch}.{audience}"'


def build_page(cur, page: str, display_id: str, audience: str = "internal",
               run: str | None = None, role: str | None = None,
               allow_history: bool = False) -> dict:
    if audience not in AUDIENCES:
        raise ApiError(400, "unknown_audience",
                       f"audience must be one of {' · '.join(AUDIENCES)}")
    sections = page_sections(page)
    if not sections:
        raise ApiError(404, "unknown_page", f"no page {page!r}")
    forbidden = page_forbidden(page, audience, role)
    if forbidden:
        raise ApiError(403, "audience_forbidden", forbidden)

    entity_id, entity, run_meta, _ = resolve_run(cur, display_id, run, allow_history)

    out_sections = {}
    for section in sections:
        r = readers()[(page, section)]
        rows = _rows(cur, r["table"], run_meta["run_id"])
        built = assemble(page, section, rows)
        if built is None:
            # A section with no serving row did not promote. Reported as an
            # explicit state rather than an empty object: blank and broken
            # must not look the same (TRD §08).
            out_sections[section] = {
                "data": None, "data_source": "empty", "provenance": None,
                "produced_at": None, "producer_version": None, "e_ids": [],
                "empty_state": {"kind": "section_not_promoted",
                                "reason": "no serving row for this run",
                                "sources_searched": []},
            }
            continue

        env, stamps = built["env"], built["stamps"]
        data, report = redact_section(page, section, built["data"],
                                      env.get("internal_only"), audience)
        if data is None:
            out_sections[section] = {
                "data": None, "data_source": "withheld", "provenance": None,
                "produced_at": None, "producer_version": None, "e_ids": [],
                "empty_state": {"kind": "withheld_for_audience",
                                "reason": "this surface is not served to the "
                                          "customer audience",
                                "sources_searched": []},
            }
            continue

        empty = env.get("empty_state")
        out_sections[section] = {
            "data": data,
            "data_source": "empty" if empty else "producer",
            "provenance": stamps.get("provenance"),
            "produced_at": (stamps.get("promoted_at").isoformat()
                            if hasattr(stamps.get("promoted_at"), "isoformat")
                            else stamps.get("promoted_at")),
            "producer_version": stamps.get("producer_version"),
            "e_ids": env.get("e_ids") or [],
            "empty_state": empty,
        }
        if audience == "customer" and report["paths_stripped"]:
            out_sections[section]["redacted_paths"] = report["paths_stripped"]

    return {"entity": entity, "run": run_meta, "audience": audience,
            "page": page, "sections": out_sections}
