"""Page endpoints — the serving tier's read path (stage 5, TRD §08).

One resolution, then one select per section. Not a wide join: a section
that failed to promote returns no row, which is a different fact from a
section that promoted empty, and a join would flatten the two into the
same nulls. Nothing here recomputes a score, delta, share or age — every
one of those is either promoted or generated by the database.
"""
from __future__ import annotations

from .computed import apply as computed_apply
from .redaction import page_forbidden, redact_section, redact_empty_state
from .subverticals import (resolve_subvertical, resolve_supplementary,
                           scope_sections)
from .serving_spec import page_sections, readers, assemble
from .value_chain import serve_value_chain

AUDIENCES = ("internal", "customer")


def _iso(v):
    """A timestamp as ISO-8601, or whatever it already was. One helper, so
    the envelope cannot format one instant two ways."""
    return v.isoformat() if hasattr(v, "isoformat") else v


class ApiError(Exception):
    def __init__(self, status: int, code: str, detail: str):
        super().__init__(detail)
        self.status, self.code, self.detail = status, code, detail


def _rows(cur, table: str, run_id) -> list[dict]:
    """Every item-grain section's rows, IN THE ORDER THE PRODUCER SENT THEM.

    `ORDER BY id` is load-bearing, not tidiness. Rule 10 is "order is
    meaning" — findings are ranked, phases sequenced, events chronological —
    and promote inserts each section's items in payload order, so the
    BIGSERIAL id IS that order. Without the clause PostgreSQL returns heap
    order, which is not insertion order, is not stable across reads, and
    changes after any UPDATE or VACUUM on the serving table.

    Measured on the reference client: `overview.firmographics.fields` served
    its first seven rows left-rotated by two — 13 in, 13 out, identical
    multiset, 7 of 13 positions carrying a different row — putting
    return-on-assets where branch count was on a ranked identity card. The
    other arrays happened to come back in insertion order on that read and
    nothing in the query made that hold on the next one. 23 of the 34
    writers are item-grain.
    """
    order = " ORDER BY id" if _has_id(cur, table) else ""
    cur.execute(f"SELECT * FROM {table} WHERE run_id = %s{order}", (run_id,))
    cols = [d[0] for d in cur.description]
    return [dict(zip(cols, r)) for r in cur.fetchall()]


_HAS_ID: dict = {}


def _has_id(cur, table: str) -> bool:
    """Whether this serving table carries the BIGSERIAL, asked once per table.

    Measured: the 23 ITEM-grain tables all have `id`; the 10 RUN-grain ones
    (overview_scores, platform_story, insights_landscape, …) do not, because
    one row per run needs no ordering. A blanket `ORDER BY id` therefore 500s
    exactly the pages carrying a run-grain section — which is what it did in
    production for the four minutes between that deploy and this fix, on
    overview and platform, while every fake-cursor test stayed green because
    a fake cursor answers whatever it is asked.

    Asked BEFORE the select, never after: a failed statement aborts the whole
    transaction in PostgreSQL and every later query on the request then fails
    with 25P02, so "try it and fall back" would take the page down anyway.
    """
    if table not in _HAS_ID:
        cur.execute("""SELECT 1 FROM information_schema.columns
                        WHERE table_schema = 'public' AND table_name = %s
                          AND column_name = 'id'""", (table,))
        _HAS_ID[table] = cur.fetchone() is not None
    return _HAS_ID[table]


def resolve_run(cur, display_id: str, run: str | None, allow_history: bool):
    """The entity and the run to serve, read from the ONE materialised view
    svc_api is granted (0013). Not the base tables: svc_api holds no SELECT
    on entities or runs by design, and resolving the active run in two
    places is how a header and its rows come to disagree."""
    cur.execute("""SELECT entity_id, display_id, legal_name, sub_vertical, size_tier,
                          run_id, request_id, run_seq, is_active, run_status,
                          composite, scored_cells, catalogue_cells,
                          ccg_catalog_version, completed_at, promoted_at,
                          assessment_date, assessment_date_basis,
                          assessment_date_source, refresh_due_date,
                          entity_domain, trading_name,
                          supplementary_sub_verticals
                     FROM serving_directory
                    WHERE display_id = %s
                    -- NULLS LAST is load-bearing: `is_active` is a nullable
                    -- boolean, and PostgreSQL sorts NULL FIRST under DESC. A
                    -- promoted run that never had the column set would
                    -- therefore sort AHEAD of the active one, and this
                    -- function would 404 an entity that is serving.
                    ORDER BY is_active DESC NULLS LAST, promoted_at DESC""",
                (display_id,))
    rows = cur.fetchall()
    if not rows:
        # No promoted run for this entity — including an entity that exists
        # but has never promoted, which is the same fact to a reader.
        raise ApiError(404, "entity_not_found",
                       f"no promoted run for {display_id!r}")
    if run:
        picked = next((r for r in rows if str(r[5]) == str(run)), None)
        if picked is None:
            raise ApiError(404, "entity_not_found",
                           f"run {run} has no promoted rows under {display_id}")
        if not picked[8] and not allow_history:
            raise ApiError(409, "run_superseded",
                           "the pinned run is no longer active; pass "
                           "history=true to read it deliberately")
    else:
        picked = rows[0]
        if not picked[8]:
            raise ApiError(404, "entity_not_found",
                           f"{display_id} has no active promoted run")

    # `trading_name` travels so a reader whose `entity_name` is NULL still
    # gets a name (the web's legal -> trading -> display id fallback), and
    # the supplementary codes so every scope call below admits the variant
    # cells of each sub-vertical the entity is bound to (0061). The display
    # label stays the PRIMARY's alone.
    entity = {"display_id": picked[1], "entity_name": picked[2],
              "trading_name": picked[21],
              "sub_vertical": picked[3], "size_tier": picked[4],
              "supplementary_sub_verticals": list(
                  resolve_supplementary(picked[22],
                                        resolve_subvertical(picked[3])))}
    run_meta = {"run_id": str(picked[5]), "request_id": picked[6],
                "run_seq": picked[7],
                "completed_at": picked[14].isoformat() if picked[14] else None,
                "promoted_at": picked[15].isoformat() if picked[15] else None,
                "ccg_catalog_version": picked[13], "scored_cells": picked[11],
                "catalogue_cells": picked[12], "status": picked[9],
                "is_active": bool(picked[8]),
                "composite": float(picked[10]) if picked[10] is not None else None,
                # The assessment date and the rung it came from travel with
                # every run this function resolves, so a page header cannot
                # render a date whose provenance the cadence block contradicts
                # (0031). `completed_at` above is retained: it is what the
                # ingest wrote, and the two agreeing is a fact worth being
                # able to check rather than one to assume.
                "assessment_date": (picked[16].isoformat()
                                    if hasattr(picked[16], "isoformat")
                                    else picked[16]),
                "assessment_date_basis": picked[17],
                "assessment_date_source": picked[18],
                "refresh_due_date": (picked[19].isoformat()
                                     if hasattr(picked[19], "isoformat")
                                     else picked[19]),
                # The entity's OWN publication domain (0045). Carried on the
                # view because svc_api holds no grant on `entities`, and read
                # here rather than queried in `computed` so the read path
                # keeps resolving the run in exactly one place.
                "entity_domain": picked[20]}
    return picked[0], entity, run_meta, picked[15]


# Bump this string whenever a SERVING RULE changes — redaction, a
# computed-at-read field, a band or thinness derivation, anything that
# changes the bytes for a run that has not been re-promoted.
#
# Why it has to exist: the tag was run_id.promoted_epoch.audience, and none
# of those three move when a serving rule is fixed. So every cached client
# would have gone on holding the defective body — including the customer body
# carrying the vendor pitch that the redaction fix removes — and the fix would
# have been invisible to exactly the readers it was for. `subverticals.py`
# already carries SCOPE_TAG for this reason; this is the same lesson at the
# page grain.
#
#   @1  the shape as it shipped
#   @2  2026-08-09 — redaction walker performs its strips; r_layer stripped
#       by key; vendor-name safety net; audience default-deny
#   @3  2026-08-09 — migration 0043 moved 30,269 duplicated re-mint links
#       and recomputed linked_evidence_count on 29,622 cells corpus-wide.
#       serving_subcaps is a live view over those counts, so the served
#       thin flags changed under an unmoved promoted_at — without this
#       bump every cached client 304s onto the inflated counts.
#   @4  2026-08-09 — the corpus excerpt repair re-minted 22,187 evidence
#       rows and its missing link carry re-created 65,425 duplicates, all
#       since removed with linked_evidence_count recomputed on 63,244
#       cells. @3 was already deployed while those counts were wrong, so a
#       body cached under it is a body cached mid-repair.
#   @5  2026-08-09 — the customer audience stops serving a named person's
#       contact route (email, linkedin_url, phone) and the enrichment tool's
#       account of itself (enrichment_basis, enriched_at), and the D2 GAPS
#       tile stops printing the vendor name twice. Both are customer-body
#       changes under an unmoved promoted_at: without this bump the reader
#       who was served the LinkedIn URL is precisely the reader who 304s
#       back onto it.
#   @6  2026-08-09 — found by a submitted-vs-served diff of all six pages.
#       Item-grain sections serve in the producer's order (ORDER BY id) and
#       not PostgreSQL heap order; `produced_at` serves the section's own
#       instant instead of the run's promotion instant, on 34 of 34 sections;
#       techstack's dma_impact withholding fires by RULE rather than by the
#       vendor safety net underneath it; and a sentence written to the
#       seller's own account executive stops reaching the customer body.
#   @7  2026-08-14 — `firmographics.website` becomes a third source for the
#       entity's own publication domains, so O11's `self_sourced_pct` changes
#       from null to a computed share on any run that states one, and its
#       `self_sourced_basis` names what closes it differently. Both are body
#       changes under an unmoved `promoted_at`, which is the whole reason this
#       tag exists: caught here only because the deployed ETag was READ after
#       the change went live and still said @6 — the reader holding a cached
#       null is exactly the reader who would 304 back onto it.
#   @8  2026-08-18 — `overview.evidence_coverage` joins CUSTOMER_WITHHELD.
#       The evidence CENSUS — tier histogram, item and fact counts, the
#       self-sourced share — was reaching the customer body in full on every
#       promoted client. It rendered nowhere only because the web adapter
#       drops those keys, so the leak was real on the wire and invisible on
#       the page, which is the worst pair: a hand check of the screen agrees
#       with a green test and neither is looking at the body. A customer who
#       fetched before this bump holds a body carrying the census.
#   @11 2026-10-02 — the SWBC redaction audit. Customer bodies change under
#       an unmoved promoted_at in five ways: the cell drawer withholds
#       internal-origin and vendor/seller/pipeline-vocabulary evidence items
#       whole and `grounded_on` counts the items served; `platform.starters`
#       is withheld whole; dict-valued `linking_stats` is held to its
#       allowlist; "account team" joins the seller net and a pipeline-
#       vocabulary net (NOT_RUN in prose, tool names, RRF, k=60…) runs over
#       every section and empty state; the value chain's empty state goes
#       through the walker. The entity block also gains `trading_name` and
#       `supplementary_sub_verticals` (0061). Before @11 was deployed it also
#       took two walker fixes from the re-check: element paths are deleted
#       highest index first, and an id-keyed map or wrapper dict is filtered
#       by its values' keys, never its ids — @11 never served without them.
#   @12 2026-10-04 — the SWBC gold audit (RC-08) and the owner's decisions
#       of that day. Customer bodies change under an unmoved promoted_at:
#       `overview.sentiment` serves a REDUCED card instead of nothing
#       (decision 1); the tech register serves CONFIRMED and ABSENT rows only
#       and its layer rollup and the insights landscape tiles follow the
#       filtered register (DECISIONS D4); platform estate_reach and
#       integration_pathway stop being hidden by an undocumented marking
#       (over-redaction, D-11); an H5 gate row about a withheld section is
#       dropped (D-34); and every citation and evidence row on a page is
#       scoped: internal spans never serve, shareable split spans serve under
#       their customer attribution (D-10, 0063).
SERVE_RULES = "serve-rules@12"


#: Keys whose value is a list of cited evidence ids (chips), and the one
#: whose value is a single cited id (a row).
_CITATION_LISTS = ("e_ids", "supporting_e_ids", "evidence_ids")


def cited_ids(data) -> set:
    """Every evidence id a section body cites, at any depth."""
    out: set = set()

    def walk(node):
        if isinstance(node, dict):
            for k, v in node.items():
                if k in _CITATION_LISTS and isinstance(v, list):
                    out.update(e for e in v if isinstance(e, str) and e)
                elif k == "e_id" and isinstance(v, str) and v:
                    out.add(v)
                else:
                    walk(v)
        elif isinstance(node, list):
            for v in node:
                walk(v)

    walk(data)
    return out


def evidence_scope(cur, entity_id, ids, *, promoted_at) -> dict:
    """Which of `ids` are INTERNAL SPANS (never served to a customer) and
    which are shareable SPLIT SPANS (served under their customer
    attribution). One entity-scoped query; ids are resolved through
    `resolve_evidence_id` exactly as the drawer resolves them (0046), so a
    superseded citation is judged by the row a reader would open.

    RC-08 / D-10: the producer's `internal_only` marking was the only thing
    between an internal-origin row and a customer chip, and on SWBC the
    whole-row marking of 20 shareable discovery rows emptied 24 drawers. The
    serve layer now decides from the stored origin and the 0063 split, and
    the marking is no longer load-bearing for either direction.

    `promoted_at` is the served run's, and it is REQUIRED: a span serves
    under its attribution only on a run promoted at or after the span was
    minted (evidence.attribution_bound). On a run promoted before, the span
    is withheld like any internal row, so a span minted for a later run
    changes nothing on the live one until a payload citing it is promoted
    (RC-08 review, 2026-10-04).
    """
    from .evidence import attribution_bound
    scope = {"withheld": set(), "attribution": {}}
    wanted = sorted(i for i in (ids or ()) if isinstance(i, str) and i)
    if not wanted:
        return scope
    cur.execute(
        """SELECT w.cited, ei.origin::text, ei.customer_attribution,
                  ei.customer_attribution_at
             FROM unnest(%s::text[]) AS w(cited)
             JOIN evidence_index ei
               ON ei.e_id = resolve_evidence_id(w.cited)
            WHERE ei.entity_id = %s""", (wanted, entity_id))
    for cited, origin, attribution, attributed_at in cur.fetchall():
        if (origin or "").lower() != "internal":
            continue
        if (isinstance(attribution, str) and attribution.strip()
                and attribution_bound(attributed_at, promoted_at)):
            scope["attribution"][cited] = attribution.strip()
        else:
            scope["withheld"].add(cited)
    return scope


def etag_for(run_meta: dict, audience: str) -> str:
    """W/"<run_id>.<promoted_at epoch>.<audience>.<serve-rules>" — the
    audience is part of the tag because one run serves two different
    documents (TRD §19), and the serving-rule tag is part of it because the
    same run also serves different documents before and after a rule
    change."""
    promoted = run_meta.get("promoted_at") or ""
    epoch = "0"
    if promoted:
        from datetime import datetime
        try:
            epoch = str(int(datetime.fromisoformat(promoted).timestamp()))
        except ValueError:
            epoch = "0"
    return f'W/"{run_meta["run_id"]}.{epoch}.{audience}.{SERVE_RULES}"'


def withheld_entry(report: dict) -> dict | None:
    """What a withheld section leaves behind in the page body.

    Two different absences. A section on the NEVER_SERVED allowlist was
    excluded by owner adjudication for EVERY audience — its key must not
    appear in the payload at all (owner, 2026-08-20: "do not include any
    surface I excluded in the live payload"). A stub with data:null still
    names the surface, which is inclusion. An audience withholding, by
    contrast, keeps the stub: the internal reader of a customer preview is
    owed the fact that a surface exists and was withheld, not a silent hole.
    """
    if report.get("never_served"):
        return None
    return {
        "data": None, "data_source": "withheld", "provenance": None,
        "produced_at": None, "producer_version": None, "e_ids": [],
        "empty_state": {"kind": "withheld_for_audience",
                        "reason": "this surface is not served to the "
                                  "customer audience",
                        "sources_searched": []},
    }


# `audience` has NO default. It used to default to "internal", which is
# fail-OPEN: unreachable over HTTP because all twelve routes pass a value
# normalised by `normalise_audience`, but a new in-process caller that
# omitted the kwarg would have been handed the full internal body in
# silence. The module that decides redaction defaults to `customer` for
# exactly this reason (redaction.normalise_audience); the function it
# decides for should not disagree with it.
def build_page(cur, page: str, display_id: str, audience: str,
               run: str | None = None, role: str | None = None,
               allow_history: bool = False) -> dict:
    if audience not in AUDIENCES:
        raise ApiError(400, "unknown_audience",
                       f"audience must be one of {' · '.join(AUDIENCES)}")
    sections = page_sections(page)
    if not sections:
        raise ApiError(404, "unknown_page", f"no page {page!r}")
    forbidden = page_forbidden(page, audience, role)
    if forbidden:
        raise ApiError(403, "audience_forbidden", forbidden)

    entity_id, entity, run_meta, _ = resolve_run(cur, display_id, run, allow_history)

    out_sections = {}
    for section in sections:
        r = readers()[(page, section)]
        if r["grain"] == "none":
            # The evidence store is not a per-run serving table: promote
            # writes no rows for it (its writer grain is "none") and it is
            # keyed by evidence id, not run. Saying so is honest; querying
            # it by run_id would be a column that does not exist. The
            # store is read through the evidence drawer, per id.
            out_sections[section] = {
                "data": None, "data_source": "external",
                "provenance": None, "produced_at": None,
                "producer_version": None, "e_ids": [],
                "empty_state": {
                    "kind": "served_from_evidence_store",
                    "reason": ("this section's rows live in the run's evidence "
                               "store and are read by evidence id rather than "
                               "by page"),
                    "sources_searched": []},
            }
            continue
        rows = _rows(cur, r["table"], run_meta["run_id"])
        built = assemble(page, section, rows)
        if page == "heatmap" and section == "value_chain":
            # H9 is SERVER-DERIVED: its contract is `fields: {}` and the
            # Backend Schema derives it by joining ccg_value_chains to
            # ccg_vc_mapping against the run's served cells. The promoted
            # row contributes only its envelope (the normal promote writes
            # envelope-only for this section); the arrangement is computed
            # here whether or not that row exists, and the empty state
            # names what was searched when the catalogue has none.
            out_sections[section] = serve_value_chain(
                cur, entity, run_meta, built, audience)
            continue
        if built is None:
            # A section with no serving row did not promote. Reported as an
            # explicit state rather than an empty object: blank and broken
            # must not look the same (TRD §08).
            out_sections[section] = {
                "data": None, "data_source": "empty", "provenance": None,
                "produced_at": None, "producer_version": None, "e_ids": [],
                "empty_state": {"kind": "section_not_promoted",
                                "reason": "no serving row for this run",
                                "sources_searched": []},
            }
            continue

        env, stamps = built["env"], built["stamps"]
        # Computed-at-read BEFORE redaction, so a census count is subject to
        # the same audience rules as a promoted one — and so a field the
        # contract calls computed is never served as the producer's copy of
        # a number the app was supposed to derive (invariant 8).
        computed_apply(cur, page, section, built["data"], run_meta, entity_id)
        # T2 SUB-VERTICAL SCOPE, on the way out.
        #
        # ET-05 already refuses a foreign variant cell at SUBMIT, so a payload
        # promoted under a resolvable sub-vertical cannot carry one. This is
        # for the payloads promoted when it was NOT resolvable: until
        # 2026-08-15 `resolve_subvertical` matched only the whole normalised
        # string, so 44 of the 93 corpus manifests carrying a sub-vertical
        # would have ingested with no scope at all — and an unresolved entity
        # keeps every cell, deliberately and silently. Widening the resolver
        # turns those entities from unscoped into scoped, which retroactively
        # makes their PROMOTED payloads wrong; the gate cannot reach back, and
        # this can.
        #
        # Same one-sided rule as everywhere else: base cells, family and
        # product variants, and an unresolved entity all keep everything.
        scope_sections(entity.get("sub_vertical"), built["data"],
                       entity.get("supplementary_sub_verticals"))
        scope = None
        if audience == "customer":
            ids = cited_ids(built["data"])
            scope = (evidence_scope(cur, entity_id, ids,
                                    promoted_at=run_meta.get("promoted_at"))
                     if ids else None)
        data, report = redact_section(page, section, built["data"],
                                      env.get("internal_only"), audience,
                                      evidence_scope=scope)
        if data is None:
            entry = withheld_entry(report)
            if entry is None:
                continue
            out_sections[section] = entry
            continue

        # THROUGH THE WALKER, not around it. This read the envelope and
        # attached the result raw, which is the whole of MEM-0137: every rule
        # in `redaction` applied to the section's content and to nothing in
        # its empty state. Measured live on three promoted clients — a
        # customer body carrying `get_evidence('platform')`, `r_layer` and
        # the literal `CUSTOMER_WITHHELD` inside
        # `platform.starters.empty_state.sources_searched`.
        empty, empty_dropped = redact_empty_state(
            env.get("empty_state"), audience)
        out_sections[section] = {
            "data": data,
            "data_source": "empty" if empty else "producer",
            "provenance": stamps.get("provenance"),
            # The instant this SECTION was produced, which is what the
            # contract's envelope says this field is, and not the instant the
            # run was promoted.
            #
            # This served `promoted_at` on 34 of 34 sections across all six
            # pages of the reference client — 0 of 34 preserved — while the
            # producer's own value sat in `env`, loaded by `assemble` from a
            # column `writer_spec` fills from `env:produced_at`, and was
            # discarded here. A page whose sections were synthesised 25 hours
            # apart by two different producers reported all of them at one
            # instant, so a reader could not tell which section was stale.
            # `promoted_at` is not lost: it is the run's, it is on the run
            # envelope, and it is in the ETag.
            "produced_at": _iso(env.get("produced_at")
                                or stamps.get("promoted_at")),
            "producer_version": stamps.get("producer_version"),
            "e_ids": env.get("e_ids") or [],
            "empty_state": empty,
        }
        removed = (len(report["paths_stripped"]) + len(report["keys_stripped"])
                   + len(report["vendor_named"]) + len(empty_dropped)
                   # Rows a customer rule held back (D4, internal spans,
                   # gate rows about withheld sections) are removals too.
                   + report.get("d4_rows_withheld", 0)
                   + report.get("evidence_scope_withheld", 0)
                   + len(report.get("gates_withheld_target") or ()))
        if audience == "customer" and removed:
            # A COUNT, not the paths. The receipt exists so a reader can tell
            # blank-because-withheld from blank-because-empty, and for that
            # the number is enough. The path strings are not: they carry the
            # field names, and `platform_story.platforms[0].zennify_pathway`
            # names the assessing vendor five times in a client's own body —
            # the leak this redaction pass exists to close, re-opened by its
            # own receipt. Measured in production after the first fix: the
            # only five occurrences left were in this list.
            out_sections[section]["redacted_count"] = removed
            out_sections[section]["redaction_note"] = (
                "fields on this surface are held for the internal audience")

    return {"entity": entity, "run": run_meta, "audience": audience,
            "page": page, "sections": out_sections}
