#!/usr/bin/env python3
"""
Pair each prototype screenshot with the corresponding production React
baseline; emit per-page pixel-divergence ratio + a markdown report.

Inputs:
  /tmp/proto-shots/proto-<route>-1440.png         (ground truth)
  apps/dma-insights/frontend/e2e/visual/responsive.visual.ts-snapshots/
    <route>-responsive-1440-linux.png             (current production)

Output:
  apps/dma-insights/docs/PROTOTYPE_DIFF_REPORT.md (table per route)
  /tmp/proto-diffs/<route>-diff.png               (visual diff image)

Per-page metric:
  - "different_pct": fraction of pixels whose RGB values differ by ANY
    amount between prototype and production. Note this is STRICT --
    even 1-pixel anti-aliasing differences count -- which is what we
    want for a "different page entirely?" signal vs. the Playwright
    2% tolerance which is for "did this page drift across runs?"
"""
from __future__ import annotations

import sys
from pathlib import Path

from PIL import Image, ImageChops

PROTO_DIR = Path("/tmp/proto-shots")
PROD_DIR = Path(
    "apps/dma-insights/frontend/e2e/visual/"
    "responsive.visual.ts-snapshots",
)
REPO_ROOT_HINTS = [Path.cwd(), Path("/home/user/Accelerate")]


def find_repo_root() -> Path:
    for r in REPO_ROOT_HINTS:
        if (r / PROD_DIR).exists():
            return r
        if (r / "apps" / "dma-insights").exists():
            return r
    raise SystemExit("Could not locate repo root. Run from frontend/.")


def diff_pair(proto_path: Path, prod_path: Path, out_path: Path) -> dict:
    proto = Image.open(proto_path).convert("RGB")
    prod = Image.open(prod_path).convert("RGB")
    # Match prod to proto's size if they diverge (full-page captures
    # have different heights in our setup -- proto's content height
    # is what we care about).
    if proto.size != prod.size:
        prod = prod.resize(proto.size)
    diff = ImageChops.difference(proto, prod)
    # Boolean mask: pixel different = any RGB delta > 0.
    bbox = diff.getbbox()
    if bbox is None:
        return {
            "pct": 0.0,
            "different_pixels": 0,
            "total_pixels": proto.size[0] * proto.size[1],
        }
    diff.save(out_path)
    # Count pixels where any channel differs.
    grey = diff.convert("L")
    histogram = grey.histogram()
    different_pixels = sum(histogram[1:])  # bin 0 = identical
    total_pixels = proto.size[0] * proto.size[1]
    return {
        "pct": (different_pixels / total_pixels) * 100,
        "different_pixels": different_pixels,
        "total_pixels": total_pixels,
    }


def main() -> int:
    root = find_repo_root()
    out_diffs = Path("/tmp/proto-diffs")
    out_diffs.mkdir(parents=True, exist_ok=True)

    proto_files = sorted(PROTO_DIR.glob("proto-*-1440.png"))
    if not proto_files:
        print(f"no prototype shots in {PROTO_DIR}", file=sys.stderr)
        return 2

    rows: list[dict] = []
    for proto_path in proto_files:
        route = proto_path.stem.removeprefix("proto-").removesuffix("-1440")
        prod_path = (
            root / PROD_DIR / f"{route}-responsive-1440-linux.png"
        )
        out_path = out_diffs / f"{route}-diff.png"
        if not prod_path.exists():
            rows.append({
                "route": route, "pct": None, "note": "no production baseline",
            })
            continue
        result = diff_pair(proto_path, prod_path, out_path)
        rows.append({
            "route": route,
            "pct": result["pct"],
            "different_pixels": result["different_pixels"],
            "total_pixels": result["total_pixels"],
            "diff_image": str(out_path),
        })

    # Render the markdown report.
    report_path = root / "apps" / "dma-insights" / "docs" / "PROTOTYPE_DIFF_REPORT.md"
    report_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Prototype-vs-Production Visual Diff",
        "",
        "Generated by `scripts/diff-prototype-vs-production.py`. Each row",
        "compares the uploaded prototype's render of a route (post-mock-auth)",
        "to the committed React production baseline (live backend + WSFS seed).",
        "",
        "**Metric**: % of pixels where any RGB channel differs by ≥1 between",
        "the two images. Strict — even subtle font-rendering shifts surface.",
        "Anything ≥40% means \"different page entirely\"; <5% means \"near-pixel-match\".",
        "",
        "| Route | Divergence | Notes |",
        "|---|---:|---|",
    ]
    for r in sorted(rows, key=lambda x: x.get("pct") if x.get("pct") is not None else -1, reverse=True):
        if r.get("pct") is None:
            lines.append(f"| `{r['route']}` | — | {r.get('note','no data')} |")
        else:
            pct = r["pct"]
            tag = "🔴" if pct >= 40 else "🟡" if pct >= 15 else "🟢"
            lines.append(f"| `{r['route']}` | {tag} {pct:.1f}% | diff `{r['diff_image']}` |")
    lines.append("")
    lines.append("## Tier interpretation")
    lines.append("- 🔴 ≥40% — port required (Batch 2-4)")
    lines.append("- 🟡 15-40% — refinement (likely class names / spacing)")
    lines.append("- 🟢 <15% — chrome variation only")

    report_path.write_text("\n".join(lines) + "\n")
    print(f"wrote {report_path}")
    for r in rows:
        if r.get("pct") is not None:
            print(f"  {r['route']:<14} {r['pct']:>6.1f}%")
        else:
            print(f"  {r['route']:<14}    n/a  ({r.get('note','')})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
