"""package_peers — per-category peer distribution from 06_peers artifacts.

Pins the two real formats (peer_comparison_table.csv with comment-line +
header-drift tolerance, and the richer peer_benchmarks.json), the
JSON-preferred resolver, and the end-to-end fill onto category_scores for
the real Greenstone package (whose category_summary ships NO peer column,
so peer benchmarks were previously dead for it).
"""
from __future__ import annotations

from pathlib import Path

from app.services.parsers.package_peers import (
    _cat_key,
    load_peer_benchmarks,
    parse_peer_benchmarks_json,
    parse_peer_comparison_csv,
)

_GREENSTONE = (
    Path(__file__).resolve().parents[1]
    / "tests/fixtures/dma_packages_batches/batch_14/Greenstone - DMA/06_peers"
)


def test_cat_key_normalises() -> None:
    assert _cat_key("P1C1_digital_strategy") == "P1C1"
    assert _cat_key("p2c3") == "P2C3"
    assert _cat_key("P10C12_x") == "P10C12"
    assert _cat_key("not-a-cat") is None
    assert _cat_key(None) is None


def test_parse_comparison_csv_real() -> None:
    p = _GREENSTONE / "peer_comparison_table.csv"
    if not p.exists():
        import pytest
        pytest.skip(f"fixture moved: {p}")
    out = parse_peer_comparison_csv(p)
    b = out["P1C1"]
    assert b.median == 2.75 and b.p25 == 2.5 and b.p75 == 4.0
    assert b.gap_vs_median == -0.25
    assert b.n == 4  # Compeer, FCMA, FCSoA, Capital FC (entity col excluded)


def test_parse_benchmarks_json_real() -> None:
    p = _GREENSTONE / "peer_benchmarks.json"
    if not p.exists():
        import pytest
        pytest.skip(f"fixture moved: {p}")
    out = parse_peer_benchmarks_json(p)
    b = out["P1C1"]
    assert b.median == 2.75 and b.p25 == 2.5 and b.p75 == 4.0
    assert b.n == 4  # peer_scores carries the 4 peers


def test_load_prefers_json() -> None:
    if not (_GREENSTONE / "peer_benchmarks.json").exists():
        import pytest
        pytest.skip("fixture moved")
    out = load_peer_benchmarks(_GREENSTONE)
    assert out and "P1C1" in out


def test_comparison_csv_tolerates_comments_and_drift(tmp_path: Path) -> None:
    p = tmp_path / "peer_comparison_table.csv"
    p.write_text(
        "# generated by bot v3\n"
        "# cohort: 3 peers\n"
        "Category,Acme,PeerA,PeerB,PeerC,peer_median,p25,p75,gap vs median,interpretation\n"
        "P1C1_digital_strategy,2.0,3.0,2.5,3.5,3.0,2.5,3.5,-1.0,BELOW MEDIAN\n"
        "P2C1_x,,,,,,,,,\n"  # no median → skipped
    )
    out = parse_peer_comparison_csv(p)
    assert set(out) == {"P1C1"}
    assert out["P1C1"].median == 3.0 and out["P1C1"].n == 3


def test_absent_returns_empty(tmp_path: Path) -> None:
    assert load_peer_benchmarks(tmp_path) == {}
    assert parse_peer_comparison_csv(tmp_path / "nope.csv") == {}
    assert parse_peer_benchmarks_json(tmp_path / "nope.json") == {}


def test_e2e_category_rollup_and_peer_fill() -> None:
    """Greenstone ships subcap-only scoring (no category_summary) + a peer
    table. parse_package should derive the 17 category rollups from subcaps
    AND fill peer median/p25/p75 from 06_peers — both previously empty."""
    from app.services.parsers.dma_package import parse_package

    root = (
        Path(__file__).resolve().parents[1]
        / "tests/fixtures/dma_packages_batches/batch_14/Greenstone - DMA"
    )
    if not root.exists():
        import pytest
        pytest.skip(f"fixture moved: {root}")
    pkg = parse_package(root)
    cats = pkg.category_scores
    assert len(cats) >= 15, "category rollup should be derived from subcaps"
    # every derived category has a sane mean score
    assert all(c.score is not None and 0 <= c.score <= 5 for c in cats)
    # peer distribution filled from the peer artifact
    assert sum(1 for c in cats if c.peer_median is not None) >= 15
    assert sum(1 for c in cats if c.peer_p25 is not None) >= 15
    p1c1 = next(c for c in cats if c.category_id == "P1C1")
    assert p1c1.peer_median == 2.75 and p1c1.peer_p25 == 2.5


def test_parse_peer_transposed_csv(tmp_path) -> None:
    from app.services.parsers.package_peers import parse_peer_transposed_csv
    p = tmp_path / "peer_comparison_table.csv"
    p.write_text(
        "Peer,Size_Tier,P1_Strategy,P2_Experience,P3_Ops\n"
        "TowneBank,Large,3.0,2.0,4.0\n"
        "PeerA,Large,2.0,3.0,3.0\n"
        "PeerB,Large,4.0,1.0,2.0\n"
    )
    out = parse_peer_transposed_csv(p)
    # pillar-keyed medians (median of 3.0/2.0/4.0 = 3.0 for P1)
    assert out["P1"].median == 3.0
    assert out["P2"].median == 2.0
    assert set(out) == {"P1", "P2", "P3"}
