/* ═══════════════════════════════════════════════════════════════════════
   DMA INSIGHTS · Admin › Usage analytics  (route: #/admin/usage · ADMIN only)
   ───────────────────────────────────────────────────────────────────────
   PRODUCTION: /api/admin/usage → BigQuery dataset filled by the dmai-usage
   log sink (lib/usage.js writes the lines, lib/usage-store.js reads them).
   Events: page_view (visible dwell per page, from usage-tracker.jsx),
   heartbeat (live now), feature, and the server-observed client_open /
   doc_load / insight_review. A session is the browser's session id, rotated
   after 30 minutes without activity. Identity is the verified session's.
   Client links (dmai-share): recipients are people with role CLIENT, their
   page beacons carry the link id, and the share service's link_* lines say
   which links were generated, opened, and refused (lib/usage LINK_EVENTS).

   Production divergences from the prototype (pages/admin-usage.jsx):
     · no team column — no team exists anywhere in this app's data
     · "Send nudge" (a toast that pretended to queue email) → a real mailto:
     · every store state is named: not configured / not recording /
       forbidden / error — never an empty chart passing as "nobody came"
     · the prior-period delta only shows where recording covers that period
   PREVIEW (no DMA_LIVE): the prototype's seeded generator, unchanged.
   ═══════════════════════════════════════════════════════════════════════ */
const { useState: useStateUA, useMemo: useMemoUA, useEffect: useEffectUA } = React;

const UA_LIVE = () => typeof window !== "undefined" && !!window.DMA_LIVE;
const UA_MOCK_NOW = new Date("2026-10-07T15:30:00");
const UA_DAY = 86400000;
const UA_LIVE_WINDOW_MS = 3 * 60 * 1000;     // heartbeat every 60 s → live within 3 min
const UA_PAGES = {
  dashboard:   { key: "dashboard",   label: "Dashboard",           dwell: [40, 140],  w: 10 },
  clients:     { key: "clients",     label: "Client directory",    dwell: [30, 110],  w: 7 },
  overview:    { key: "overview",    label: "Client · Overview",   dwell: [90, 420],  w: 14, client: true },
  insights:    { key: "insights",    label: "Client · Insights",   dwell: [80, 360],  w: 9,  client: true },
  heatmap:     { key: "heatmap",     label: "Client · Heatmap",    dwell: [120, 600], w: 10, client: true },
  platform:    { key: "platform",    label: "Client · Platform",   dwell: [100, 480], w: 9,  client: true },
  context:     { key: "context",     label: "Client · Context",    dwell: [60, 260],  w: 4,  client: true },
  techstack:   { key: "techstack",   label: "Client · Tech stack", dwell: [50, 240],  w: 4,  client: true },
  health:      { key: "health",      label: "Client · Health",     dwell: [60, 300],  w: 3,  client: true, roles: ["ANALYST", "ADMIN"] },
  runs:        { key: "runs",        label: "Client · Runs",       dwell: [20, 120],  w: 2,  client: true },
  alerts:      { key: "alerts",      label: "Alerts",              dwell: [40, 240],  w: 4,  roles: ["ANALYST", "ADMIN"] },
  prospecting: { key: "prospecting", label: "Prospecting",         dwell: [60, 300],  w: 4 },
  admin:       { key: "admin",       label: "Admin",               dwell: [40, 260],  w: 5,  roles: ["ADMIN"] },
};
// Production-only page keys (lib/usage.js pageOf) — never generated by the mock.
const UA_EXTRA_LABEL = { admin_usage: "Admin · Usage analytics", login: "Sign-in", other: "Other" };
const uaLabel = k => (UA_PAGES[k] && UA_PAGES[k].label) || UA_EXTRA_LABEL[k] || k;
// Usage colours stay OFF the maturity-band ramp (gate N, invariant 7): a fill
// on this page means a page or a role, never a maturity level.
const UA_PAGE_COLOR = { dashboard: "#1C4A4D", clients: "#9AA9AA", overview: "#3B82C4", insights: "#735BA1", heatmap: "#D66D2A", platform: "#2E7DAF", context: "#5B8DB8", techstack: "#7FB7A4", health: "#C25B5B", runs: "#B9A27A", alerts: "#D99A3A", prospecting: "#8C6BB8", admin: "#3D5A5C", admin_usage: "#3D5A5C", login: "#9AA9AA", other: "#9AA9AA" };
// CLIENT is a client-link reader on the public share service (lib/usage):
// not a grant, never offered a role, but a person whose reading is measured.
const UA_ROLE_COLOR = { AE: "#3B82C4", ANALYST: "#735BA1", ADMIN: "#D66D2A", CLIENT: "#B5487A" };
const UA_STAFF = ["AE", "ANALYST", "ADMIN"];
const UA_ROLES_ALL = ["AE", "ANALYST", "ADMIN", "CLIENT"];
const UA_FILL = "#3B82C4";   // single-series bars and the hour heatmap
const UA_ROLE_LABEL = { AE: "AE", ANALYST: "Analyst", ADMIN: "Admin", CLIENT: "Client" };
// Feature actions, in display order. The prototype's meeting_prep / ae_note /
// export do not exist as actions in production; insight_review (an Accept or
// Reject on an insight card, logged by the server on success) does.
const UA_FEATURES_PROTO = [
  ["intelligence", "Intelligence panel opens"], ["evidence", "Evidence drawers opened"],
  ["meeting_prep", "Meeting prep generated"], ["ae_note", "AE notes added"], ["export", "Exports"],
];
const UA_FEATURES_LIVE = [
  ["evidence", "Evidence drawers opened"], ["insight", "Insight cards opened"],
  ["intelligence", "Intelligence panel opens"], ["insight_review", "Insight verdicts recorded"],
  ["client_link", "Client links created"],
];
const uaFeatures = () => UA_LIVE() ? UA_FEATURES_LIVE : UA_FEATURES_PROTO;

/* ── preview-only mock (the prototype's seeded generator) ─────────── */
const UA_USERS = [
  { email: "mishley.andrade@zennify.com", name: "Mishley Andrade", role: "ANALYST", level: 5.5, team: "DMA Research" },
  { email: "dev.patel@zennify.com",       name: "Dev Patel",       role: "ADMIN",   level: 4,   team: "Platform" },
  { email: "sara.lin@zennify.com",        name: "Sara Lin",        role: "AE",      level: 6,   team: "FSI · East" },
  { email: "priya.nair@zennify.com",      name: "Priya Nair",      role: "AE",      level: 5,   team: "FSI · Central" },
  { email: "jordan.kim@zennify.com",      name: "Jordan Kim",      role: "AE",      level: 4.2, team: "FSI · West" },
  { email: "alex.morgan@zennify.com",     name: "Alex Morgan",     role: "ANALYST", level: 4.5, team: "DMA Research" },
  { email: "nina.shah@zennify.com",       name: "Nina Shah",       role: "AE",      level: 4.8, team: "Wealth & AM", since: 26 },
  { email: "chris.oduya@zennify.com",     name: "Chris Oduya",     role: "AE",      level: 3.4, team: "Wealth & AM" },
  { email: "sam.whitfield@zennify.com",   name: "Sam Whitfield",   role: "ANALYST", level: 3,   team: "DMA Research" },
  { email: "lena.fischer@zennify.com",    name: "Lena Fischer",    role: "AE",      level: 2.8, team: "Insurance" },
  { email: "maria.gomez@zennify.com",     name: "Maria Gomez",     role: "AE",      level: 2.2, team: "Credit Unions" },
  { email: "tom.reyes@zennify.com",       name: "Tom Reyes",       role: "AE",      level: 3,   team: "FSI · East", quiet: 22 },
  { email: "ben.carter@zennify.com",      name: "Ben Carter",      role: "AE",      level: 1.5, team: "Farm Credit", quiet: 41 },
];
function uaRand(seed) { let a = seed >>> 0; return () => { a = (a + 0x6D2B79F5) >>> 0; let t = a; t = Math.imul(t ^ (t >>> 15), t | 1); t ^= t + Math.imul(t ^ (t >>> 7), t | 61); return ((t ^ (t >>> 14)) >>> 0) / 4294967296; }; }
function uaPick(rnd, arr, wfn) { const tot = arr.reduce((s, x) => s + wfn(x), 0); let r = rnd() * tot; for (const x of arr) { r -= wfn(x); if (r <= 0) return x; } return arr[arr.length - 1]; }
function uaSession(rnd, u, start, ents, sid) {
  const allowed = Object.values(UA_PAGES).filter(p => !p.roles || p.roles.includes(u.role));
  const n = 3 + Math.floor(rnd() * 9);
  let client = ents[Math.floor(rnd() * ents.length)];
  const pages = [], features = [];
  let t = start.getTime();
  for (let i = 0; i < n; i++) {
    const pg = i === 0 && rnd() < 0.7 ? UA_PAGES.dashboard : uaPick(rnd, allowed, p => p.w * (u.role === "AE" && (p.key === "platform" || p.key === "overview") ? 1.5 : 1) * (u.role === "ANALYST" && (p.key === "heatmap" || p.key === "health") ? 1.6 : 1));
    if (pg.client && rnd() < 0.18) client = ents[Math.floor(rnd() * ents.length)];
    const secs = Math.round(pg.dwell[0] + rnd() * (pg.dwell[1] - pg.dwell[0]));
    pages.push({ key: pg.key, label: pg.label, client: pg.client ? client.id : null, clientName: pg.client ? client.name : null, at: new Date(t), secs, view: true });
    if ((pg.key === "overview" || pg.key === "platform") && rnd() < 0.3) features.push("intelligence");
    if ((pg.key === "overview" || pg.key === "heatmap" || pg.key === "insights") && rnd() < 0.4) features.push("evidence");
    if (pg.key === "platform" && u.role === "AE" && rnd() < 0.28) features.push("ae_note");
    if (pg.key === "overview" && u.role === "AE" && rnd() < 0.18) features.push("meeting_prep");
    if (rnd() < 0.05) features.push("export");
    t += secs * 1000;
  }
  return { id: "S-" + sid, email: u.email, role: u.role, start, end: new Date(t), secs: Math.round((t - start.getTime()) / 1000), pages, features: features.map(f => ({ f, at: start })), device: rnd() < 0.86 ? "Desktop · Chrome" : (rnd() < 0.5 ? "Desktop · Safari" : "iPad · Safari") };
}
let UA_MOCK_CACHE = null;
function uaMockModel() {
  if (UA_MOCK_CACHE) return UA_MOCK_CACHE;
  const rnd = uaRand(20261007);
  const ents = (DMA.ENTITIES || []).map(e => ({ id: e.id, name: e.name }));
  const sessions = []; let sid = 1000;
  const base = new Date(UA_MOCK_NOW); base.setHours(0, 0, 0, 0);
  for (let d = 179; d >= 0; d--) {
    const day = new Date(base.getTime() - d * UA_DAY);
    const weekend = day.getDay() === 0 || day.getDay() === 6;
    UA_USERS.forEach((u, ui) => {
      if (u.quiet && d < u.quiet) return;
      if (u.since && d >= u.since) return;
      const trend = 0.8 + 0.35 * Math.sin((180 - d) / 11 + ui * 1.7) + (180 - d) / 180 * 0.25;
      const p = Math.min(0.95, (u.level / 5) * (weekend ? 0.08 : 0.82) * trend);
      let n = rnd() < p ? 1 : 0; if (n && rnd() < p * 0.4) n = 2;
      for (let k = 0; k < n; k++) {
        const h = 8 + Math.floor(rnd() * 9) + k, m = Math.floor(rnd() * 60);
        if (d === 0 && h >= 15) continue;
        sessions.push(uaSession(rnd, u, new Date(day.getTime() + h * 3600000 + m * 60000), ents, sid++));
      }
    });
  }
  [["sara.lin@zennify.com", 4], ["mishley.andrade@zennify.com", 12], ["priya.nair@zennify.com", 21]].forEach(([em, m]) => {
    const s = uaSession(rnd, UA_USERS.find(x => x.email === em), new Date(base.getTime() + 15 * 3600000 + m * 60000), ents, sid++);
    while (s.pages.length > 1 && s.pages[s.pages.length - 1].at >= UA_MOCK_NOW) s.pages.pop();
    const last = s.pages[s.pages.length - 1];
    last.secs = Math.round((UA_MOCK_NOW - last.at) / 1000);
    s.end = UA_MOCK_NOW; s.secs = Math.round((UA_MOCK_NOW - s.start) / 1000); s.live = true;
    sessions.push(s);
  });
  sessions.sort((a, b) => a.start - b.start);
  const people = UA_USERS.map(u => ({ email: u.email, name: u.name, role: u.role, team: u.team }));
  const lastSeen = {};
  sessions.forEach(s => { lastSeen[s.email] = s.end; });
  UA_MOCK_CACHE = { status: "ok", now: UA_MOCK_NOW, sessions, people, lastSeen, recordingSince: sessions[0] ? sessions[0].start : null, truncated: false };
  return UA_MOCK_CACHE;
}

/* ── production model: the wire rows → the same shape the views read ── */
function uaNameOf(email) {
  if (typeof window !== "undefined" && typeof window.displayNameOf === "function") return window.displayNameOf(email);
  const parts = String(email || "").split("@")[0].split(/[._-]+/).filter(Boolean);
  if (parts.length === 1 && parts[0].length <= 3) return parts[0].toUpperCase();
  return parts.map(w => w[0].toUpperCase() + w.slice(1)).join(" ") || email;
}
function uaClientName(id) {
  const e = (DMA.ENTITIES || []).find(x => x.id === id || x.display_id === id);
  return e ? entityName(e) : id;
}
function uaModelFromWire(body) {
  const now = new Date(body.generated_at || Date.now());
  const F = body.fields || [];
  const ix = Object.fromEntries(F.map((f, i) => [f, i]));
  const rows = (body.events || []).map(r => Object.fromEntries(F.map(f => [f, r[ix[f]]])));
  const bySid = new Map();
  const featureEvents = [];
  const linkEvents = [];
  const roleOf = {};
  rows.forEach(r => {
    // A Zennify role always wins over CLIENT: someone on staff who opens a
    // client link to check it is still staff.
    if (r.email && r.role && (r.role !== "CLIENT" || !roleOf[r.email])) roleOf[r.email] = r.role;
    const t = new Date(r.t);
    if (r.type === "feature" && r.feature) featureEvents.push({ email: r.email, f: r.feature, at: t, sid: r.sid || null });
    if (r.type && r.type.indexOf("link_") === 0) {
      linkEvents.push({ type: r.type, email: r.email || null, at: t, jti: r.link_jti || null, client: r.client_id || null,
                        method: r.method || null, attempted: r.attempted_email || null, reason: r.reason || null });
      return;
    }
    if (!r.sid || (r.type !== "page_view" && r.type !== "heartbeat" && r.type !== "feature")) return;
    let s = bySid.get(r.sid);
    if (!s) { s = { id: r.sid, email: r.email, role: r.role, link: r.link_jti || null, start: t, end: t, secs: 0, pages: [], features: [], device: r.device || "", lastBeat: null }; bySid.set(r.sid, s); }
    if (t > s.end) s.end = t;
    if (r.type === "heartbeat") { s.lastBeat = t; s.livePage = r.page; s.liveClient = r.client_id; return; }
    if (r.type === "feature") { s.features.push({ f: r.feature, at: t }); return; }
    // page_view: the visit begins at entered_at (browser clock, kept only when
    // plausible) or, without it, at the moment it was reported less its dwell.
    const secs = Math.max(0, Math.round((r.dwell_ms || 0) / 1000));
    const at = r.entered_at ? new Date(r.entered_at) : new Date(t.getTime() - secs * 1000);
    if (at < s.start) s.start = at;
    s.secs += secs;
    const prev = [...s.pages].reverse().find(p => p.key === r.page && p.client === (r.client_id || null));
    if (r.cont && prev) { prev.secs += secs; return; }
    s.pages.push({ key: r.page, label: uaLabel(r.page), client: r.client_id || null, clientName: r.client_id ? uaClientName(r.client_id) : null, at, secs, view: !r.cont });
  });
  const sessions = [...bySid.values()].map(s => {
    s.pages.sort((a, b) => a.at - b.at);
    s.live = !!(s.lastBeat && now - s.lastBeat < UA_LIVE_WINDOW_MS);
    if (s.live && s.livePage && (!s.pages.length || s.pages[s.pages.length - 1].key !== s.livePage || s.pages[s.pages.length - 1].client !== (s.liveClient || null))) {
      // On a page right now, not yet reported (a page_view is sent on leave).
      s.pages.push({ key: s.livePage, label: uaLabel(s.livePage), client: s.liveClient || null, clientName: s.liveClient ? uaClientName(s.liveClient) : null, at: s.lastBeat, secs: 0, view: true, now: true });
    }
    return s;
  }).filter(s => s.pages.length || s.features.length).sort((a, b) => a.start - b.start);
  // Server-side features (insight verdicts) carry no browser session.
  const sessionless = featureEvents.filter(e => !e.sid);
  // People: everyone granted a role, plus everyone who has ever been seen.
  const g = (window.DMA_LIVE && window.DMA_LIVE.role_grants) || { admins: [], analysts: [] };
  const lastSeen = {};
  Object.entries(body.last_seen || {}).forEach(([e, iso]) => { lastSeen[e] = new Date(iso); });
  // Client links generated (every one retained, lib/usage-store linksSql).
  // Their recipients are people too: a recipient who has never opened the
  // link is "No activity yet", not missing.
  const LF = body.link_fields || [];
  const lx = Object.fromEntries(LF.map((f, i) => [f, i]));
  const links = (body.links || []).map(a => ({
    jti: a[lx.jti], at: new Date(a[lx.t]), by: a[lx.by] || null, byRole: a[lx.by_role] || null,
    client: a[lx.client_id] || null, clientName: a[lx.client_id] ? uaClientName(a[lx.client_id]) : null,
    run: a[lx.run_id] || null, recipients: a[lx.recipients] || [], domains: a[lx.domains] || [],
    expires: a[lx.expires_at] ? new Date(a[lx.expires_at]) : null,
  })).filter(l => l.jti);
  const clientOf = {};
  links.forEach(l => l.recipients.forEach(e => { clientOf[e] = l.clientName; }));
  linkEvents.forEach(e => { if (e.email && e.client) clientOf[e.email] = uaClientName(e.client); });
  sessions.forEach(s => { if (s.role === "CLIENT" && s.pages.length && s.pages[0].clientName) clientOf[s.email] = clientOf[s.email] || s.pages[0].clientName; });
  const clientOnly = new Set((body.client_only || []).map(e => e.toLowerCase()));
  const staff = new Set([...(g.admins || []), ...(g.analysts || [])].map(e => e.toLowerCase()));
  links.forEach(l => l.recipients.forEach(e => { if (!staff.has(e) && !(roleOf[e] && roleOf[e] !== "CLIENT")) clientOnly.add(e); }));
  Object.keys(lastSeen).forEach(e => { if (roleOf[e] && roleOf[e] !== "CLIENT") clientOnly.delete(e); });
  const emails = new Set([...(g.admins || []), ...(g.analysts || []), ...Object.keys(lastSeen), ...clientOnly].map(e => e.toLowerCase()));
  const grantRole = e => (g.admins || []).includes(e) ? "ADMIN" : (g.analysts || []).includes(e) ? "ANALYST" : clientOnly.has(e) ? "CLIENT" : "AE";
  const people = [...emails].map(email => {
    const role = roleOf[email] && !(roleOf[email] === "CLIENT" && staff.has(email)) ? roleOf[email] : grantRole(email);
    return { email, name: uaNameOf(email), role, team: role === "CLIENT" && clientOf[email] ? `Client link · ${clientOf[email]}` : undefined };
  });
  return { status: "ok", now, sessions, sessionless, people, lastSeen, links, linkEvents,
           clientOnly: new Set(people.filter(u => u.role === "CLIENT").map(u => u.email)),
           recordingSince: body.recording_since ? new Date(body.recording_since) : null,
           truncated: !!body.truncated, awaiting: !!body.awaiting_first_event };
}

/* One fetch per range per minute, shared by the page, the admin-home glance
   card and the Users & roles card. */
const UA_FETCH = {};
function useUsageModel(rangeDays) {
  const live = UA_LIVE();
  const [state, setState] = useStateUA(() => live ? (UA_FETCH[rangeDays] && UA_FETCH[rangeDays].model) || { status: "loading" } : uaMockModel());
  useEffectUA(() => {
    if (!live) { setState(uaMockModel()); return; }
    let cancelled = false;
    const hit = UA_FETCH[rangeDays];
    if (hit && hit.model && Date.now() - hit.at < 60000) { setState(hit.model); return; }
    setState(s => s.status === "ok" ? s : { status: "loading" });
    (hit && hit.inflight && Date.now() - hit.at < 60000 ? hit.inflight : (UA_FETCH[rangeDays] = { at: Date.now(), inflight:
      fetch(`/api/admin/usage?days=${rangeDays}`)
        .then(r => r.json().then(b => ({ ok: r.ok, b })))
        .then(({ ok, b }) => ok && b.status === "ok" ? uaModelFromWire(b)
                            : { status: (b && (b.status || b.error)) || "error", detail: b && b.detail })
        .catch(() => ({ status: "unreachable" })) }).inflight)
      .then(model => { UA_FETCH[rangeDays] = { at: Date.now(), model }; if (!cancelled) setState(model); });
    return () => { cancelled = true; };
  }, [rangeDays, live]);
  return state;
}

/* ── aggregation ────────────────────────────────────────────────── */
function uaAgg(model, from, to, onlyEmail) {
  const S = model.sessions.filter(s => s.start >= from && s.start < to && (!onlyEmail || s.email === onlyEmail));
  const days = Math.max(1, Math.round((to - from) / UA_DAY));
  const daily = Array.from({ length: days }, () => ({ AE: 0, ANALYST: 0, ADMIN: 0, CLIENT: 0, mins: 0, users: new Set() }));
  const users = new Set(), pages = {}, clients = {}, feat = {};
  const heat = Array.from({ length: 7 }, () => Array(24).fill(0));
  let secs = 0, views = 0;
  S.forEach(s => {
    users.add(s.email); secs += s.secs;
    const d = daily[Math.floor((s.start - from) / UA_DAY)];
    if (d) { d[s.role] = (d[s.role] || 0) + 1; d.mins += s.secs / 60; d.users.add(s.email); }
    s.features.forEach(x => { feat[x.f] = (feat[x.f] || 0) + 1; });
    s.pages.forEach(p => {
      // The page someone is on right now is shown in Live now and in the
      // session path; it becomes a view, with its time, once it is reported.
      if (p.now) return;
      const P = pages[p.key] || (pages[p.key] = { key: p.key, label: p.label, views: 0, secs: 0, users: new Set() });
      if (p.view) { P.views++; views++; heat[(p.at.getDay() + 6) % 7][p.at.getHours()]++; }
      P.secs += p.secs; P.users.add(s.email);
      if (p.client) { const C = clients[p.client] || (clients[p.client] = { id: p.client, name: p.clientName, views: 0, secs: 0, users: new Set() }); if (p.view) C.views++; C.secs += p.secs; C.users.add(s.email); }
    });
  });
  (model.sessionless || []).forEach(e => {
    if (e.at >= from && e.at < to && (!onlyEmail || e.email === onlyEmail)) { feat[e.f] = (feat[e.f] || 0) + 1; users.add(e.email); }
  });
  // A client reader who opened their link is a user of the period even if
  // their browser's page beacons never arrived (blocked, closed at once).
  (model.linkEvents || []).forEach(e => {
    if (e.type === "link_open" && e.email && e.at >= from && e.at < to && (!onlyEmail || e.email === onlyEmail)) users.add(e.email);
  });
  return { S, users, secs, views, sessions: S.length, avg: S.length ? secs / S.length : 0, pps: S.length ? views / S.length : 0,
    pages: Object.values(pages).sort((a, b) => b.secs - a.secs), clients: Object.values(clients).sort((a, b) => b.secs - a.secs), feat, heat, daily };
}
/* The model narrowed to a set of people: every figure computed from it is
   about them and nobody else. Recording bounds and `now` stay the store's. */
function uaNarrow(model, emails) {
  // A link stays in view while its sharer, a recipient or a reader does; a
  // refusal (no person behind it) only alongside a link that stays.
  const ev = model.linkEvents || [];
  const links = (model.links || []).filter(l => emails.has(l.by) || l.recipients.some(e => emails.has(e))
    || ev.some(e => e.jti === l.jti && e.email && emails.has(e.email)));
  const kept = new Set([...links.map(l => l.jti), ...ev.filter(e => e.email && emails.has(e.email)).map(e => e.jti)]);
  return { ...model,
    sessions: model.sessions.filter(s => emails.has(s.email)),
    sessionless: (model.sessionless || []).filter(e => emails.has(e.email)),
    people: model.people.filter(u => emails.has(u.email)),
    links,
    linkEvents: ev.filter(e => e.email ? emails.has(e.email) : kept.has(e.jti)),
  };
}

/* Per link, for the period: who shared it, who it went to, who opened it, and
   what they read. Reading time comes from the readers' own sessions, which
   carry the link id; opens and refusals from the share service's lines. */
function uaLinkRows(model, from, to) {
  const ev = model.linkEvents || [];
  const known = new Set((model.links || []).map(l => l.jti));
  // A link with readers in range whose mint line predates retention still shows.
  const orphan = {};
  ev.forEach(e => { if (e.jti && !known.has(e.jti) && !orphan[e.jti]) orphan[e.jti] = { jti: e.jti, at: null, by: null, client: e.client, clientName: e.client ? uaClientName(e.client) : null, recipients: [], domains: [], expires: null }; });
  return [...(model.links || []), ...Object.values(orphan)].map(l => {
    const mine = ev.filter(e => e.jti === l.jti);
    const inRange = mine.filter(e => e.at >= from && e.at < to);
    const S = model.sessions.filter(s => s.link === l.jti && s.start >= from && s.start < to);
    const readers = new Set([...inRange.filter(e => e.type === "link_open" && e.email).map(e => e.email), ...S.map(s => s.email)]);
    const everOpened = new Set(mine.filter(e => (e.type === "link_open" || e.type === "link_admit") && e.email).map(e => e.email));
    const opens = mine.filter(e => e.type === "link_open").map(e => e.at);
    return { ...l, readers, everOpened,
      opens: inRange.filter(e => e.type === "link_open").length,
      refused: inRange.filter(e => e.type === "link_refused").length,
      views: S.reduce((a, s) => a + s.pages.filter(p => p.view).length, 0),
      secs: S.reduce((a, s) => a + s.secs, 0),
      last: opens.length ? new Date(Math.max(...opens)) : null,
      unopened: l.recipients.filter(e => !everOpened.has(e)),
      created: !!(l.at && l.at >= from && l.at < to) };
  }).filter(r => r.created || r.opens || r.refused || r.secs || r.views)
    .sort((a, b) => (b.last || b.at || 0) - (a.last || a.at || 0));
}
/* A prior-period comparison is only honest where recording covered it. */
function uaPrevCovered(model, prevFrom) { return !!(model.recordingSince && model.recordingSince <= prevFrom); }
function uaDur(s) { s = Math.round(s); if (s < 60) return `${s}s`; if (s < 3600) return `${Math.floor(s / 60)}m ${String(s % 60).padStart(2, "0")}s`; return `${Math.floor(s / 3600)}h ${String(Math.floor(s % 3600 / 60)).padStart(2, "0")}m`; }
function uaRel(d, live, now) { if (live) return "Live now"; if (!d) return "Never"; const m = (now - d) / 60000; if (m < 60) return `${Math.max(1, Math.round(m))}m ago`; if (m < 1440) return `${Math.round(m / 60)}h ago`; const dd = Math.round(m / 1440); return dd === 1 ? "Yesterday" : `${dd}d ago`; }
function uaTime(d) { return d.toLocaleTimeString([], { hour: "numeric", minute: "2-digit" }); }
function uaDate(d) { return d.toLocaleDateString([], { weekday: "short", month: "short", day: "numeric" }); }
function uaCsv(S, name) {
  const rows = [["session_id", "email", "role", "session_started", "session_secs", "page", "client", "entered_at", "dwell_secs"]];
  S.forEach(s => s.pages.forEach(p => rows.push([s.id, s.email, s.role, s.start.toISOString(), s.secs, p.label, p.clientName || "", p.at.toISOString(), p.secs])));
  const blob = new Blob([rows.map(r => r.map(v => `"${String(v).replace(/"/g, '""')}"`).join(",")).join("\n")], { type: "text/csv" });
  const a = document.createElement("a"); a.href = URL.createObjectURL(blob); a.download = name; document.body.appendChild(a); a.click(); a.remove();
}
const uaInitials = n => String(n || "?").split(" ").map(x => x[0]).slice(0, 2).join("");
function uaDayBounds(now, range) {
  const b = new Date(now); b.setHours(0, 0, 0, 0);
  const to = new Date(b.getTime() + UA_DAY);
  return { from: new Date(to.getTime() - range * UA_DAY), to };
}
function uaRows(model, cur, to) {
  return model.people.map(u => {
    const all = model.sessions.filter(s => s.email === u.email), mine = cur.S.filter(s => s.email === u.email);
    const live = all.some(s => s.live);
    const last = model.lastSeen[u.email] || (all.length ? all[all.length - 1].end : null);
    const secs = mine.reduce((a, s) => a + s.secs, 0);
    const pg = {}; mine.forEach(s => s.pages.forEach(p => { pg[p.label] = (pg[p.label] || 0) + p.secs; }));
    const top = Object.entries(pg).sort((a, b) => b[1] - a[1])[0];
    const spark = Array(14).fill(0);
    all.forEach(s => { const di = 13 - Math.floor((to - s.start) / UA_DAY); if (di >= 0 && di < 14) spark[di] += s.secs / 60; });
    const since = last ? (model.now - last) / UA_DAY : null;
    const status = live ? "Live" : since == null ? "Never" : since < 7 ? "Active" : since < 30 ? "Idle" : "Dormant";
    return { ...u, sessions: mine.length, secs, views: mine.reduce((a, s) => a + s.pages.filter(p => p.view).length, 0), avg: mine.length ? secs / mine.length : 0,
      last, live, top: top ? top[0] : "No page views", spark, status };
  });
}

/* ── atoms ──────────────────────────────────────────────────────── */
function UAKpi({ label, value, cur, prev, sub }) {
  const delta = prev ? (cur - prev) / prev : null;
  const up = delta != null && delta >= 0;
  return (
    <div className="card" style={{ padding: "14px 16px" }}>
      <div style={{ fontSize: 10.5, color: "var(--z-muted)", textTransform: "uppercase", letterSpacing: ".06em", fontWeight: 600 }}>{label}</div>
      <div style={{ fontSize: 28, fontWeight: 300, color: "var(--z-dark)", marginTop: 4, fontVariantNumeric: "tabular-nums" }}>{value}</div>
      <div style={{ display: "flex", gap: 6, alignItems: "center", marginTop: 2, fontSize: 11 }}>
        {delta != null ? <span style={{ color: up ? "var(--z-mid)" : "var(--z-org)", fontWeight: 600 }}>{up ? "▲" : "▼"} {Math.abs(delta * 100).toFixed(0)}%</span> : null}
        <span style={{ color: "var(--z-muted)" }}>{delta != null ? (sub || "vs previous period") : "no prior period recorded"}</span>
      </div>
    </div>
  );
}
function UASpark({ vals, color = UA_FILL, h = 22 }) {
  const max = Math.max(1, ...vals);
  return <div style={{ display: "flex", alignItems: "flex-end", gap: 2, height: h, width: 84 }}>{vals.map((v, i) => <div key={i} style={{ flex: 1, height: `${Math.max(v ? 8 : 4, v / max * 100)}%`, background: v ? color : "var(--z-sep)", borderRadius: 1 }} />)}</div>;
}
/* Sessions per day, stacked by role. One measure, not a toggle between three
   (owner, 2026-10-08: "the daily activity toggle feels off"): active time and
   people per day were the KPI tiles' numbers restated as different charts,
   and only one of the three carried the role legend. Each day's tooltip
   still gives all of them. The one person's drawer draws minutes instead
   (`minutes`), because for a single person roles do not split anything. */
function UADailyChart({ daily, from, minutes }) {
  const vals = daily.map(d => minutes ? d.mins : d.AE + d.ANALYST + d.ADMIN + (d.CLIENT || 0));
  const max = Math.max(1, ...vals), n = daily.length, every = n <= 7 ? 1 : n <= 30 ? 5 : 15;
  const gap = n > 60 ? 1 : n > 20 ? 3 : 10;
  return (
    <div>
      <div style={{ display: "flex", alignItems: "flex-end", gap, height: 170, borderBottom: "1px solid var(--z-sep)" }}>
        {daily.map((d, i) => {
          const date = new Date(from.getTime() + i * UA_DAY);
          const parts = UA_ROLES_ALL.filter(r => d[r]).map(r => `${UA_ROLE_LABEL[r]} ${d[r]}`).join(" · ");
          const tip = minutes ? `${uaDate(date)} · ${uaDur(d.mins * 60)} active` : vals[i]
            ? `${uaDate(date)} · ${vals[i]} ${vals[i] === 1 ? "session" : "sessions"}${parts ? ` (${parts})` : ""} · ${d.users.size} ${d.users.size === 1 ? "person" : "people"} · ${uaDur(d.mins * 60)} active`
            : `${uaDate(date)} · no sessions`;
          return (
            <div key={i} title={tip} style={{ flex: 1, minWidth: 0, height: "100%", display: "flex", flexDirection: "column", justifyContent: "flex-end", gap: 1, cursor: "default" }}>
              {minutes
                ? <div style={{ height: `${vals[i] / max * 100}%`, minHeight: vals[i] ? 2 : 0, background: UA_FILL, borderRadius: "3px 3px 0 0" }} />
                : ["CLIENT", "ADMIN", "ANALYST", "AE"].map(r => d[r] ? <div key={r} style={{ height: `${d[r] / max * 100}%`, background: UA_ROLE_COLOR[r], borderRadius: 2 }} /> : null)}
            </div>
          );
        })}
      </div>
      <div style={{ display: "flex", gap, marginTop: 6 }}>
        {daily.map((d, i) => <div key={i} style={{ flex: 1, minWidth: 0, fontSize: 9.5, color: "var(--z-muted)", whiteSpace: "nowrap", overflow: "visible" }}>{i % every === 0 ? new Date(from.getTime() + i * UA_DAY).toLocaleDateString([], { month: "short", day: "numeric" }) : ""}</div>)}
      </div>
    </div>
  );
}
function UAHourHeat({ heat }) {
  const hours = Array.from({ length: 14 }, (_, i) => i + 7), days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
  const max = Math.max(1, ...heat.flat());
  return (
    <div style={{ display: "grid", gridTemplateColumns: "34px repeat(14, minmax(0,1fr))", gap: 3 }}>
      <div />
      {hours.map(h => <div key={h} style={{ fontSize: 9.5, color: "var(--z-muted)", textAlign: "center" }}>{h > 12 ? h - 12 : h}{h >= 12 ? "p" : "a"}</div>)}
      {days.map((d, di) => (
        <React.Fragment key={d}>
          <div style={{ fontSize: 10.5, color: "var(--z-muted)", display: "flex", alignItems: "center" }}>{d}</div>
          {hours.map(h => { const v = heat[di][h]; return <div key={h} title={`${d} ${h}:00–${h + 1}:00 · ${v} page views`} style={{ height: 22, borderRadius: 4, background: v ? `rgba(59,130,196,${0.1 + 0.9 * v / max})` : "var(--z-bg)" }} />; })}
        </React.Fragment>
      ))}
    </div>
  );
}
function UAStatus({ status }) {
  const cls = { Live: "b-teal", Active: "b-above", Idle: "b-org", Dormant: "b-muted", Never: "b-muted" }[status];
  return <span className={`b b-token ${cls}`} style={{ display: "inline-flex", gap: 4, alignItems: "center" }}>{status === "Live" ? <span className="live-dot" /> : null}{status === "Never" ? "No activity yet" : status}</span>;
}

/* The store's non-ok states, by name. */
const UA_STATE_COPY = {
  loading: ["Loading usage…", "Reading the usage dataset."],
  not_configured: ["Usage recording is not configured", "This deployment has no usage dataset (USAGE_DATASET). It is set by infra/deploy.sh."],
  not_recording: ["Not recording yet", "The usage dataset does not exist yet. The release creates it together with the dmai-usage log sink; usage counts from that moment, with no backfill."],
  forbidden: ["Usage data is not readable", "The web service account is missing a BigQuery grant. The release applies it; the line below names which one."],
  unreachable: ["Usage service unreachable", "The request to /api/admin/usage did not complete."],
  admin_session_required: ["Admin access required", "Usage analytics needs an ADMIN grant."],
  error: ["Usage data could not be read", null],
};
/* The sink is live and nothing has reached it yet: the layout renders at
   zero, and this line says why the zeros are not "nobody came". */
function UAAwaiting({ compact }) {
  return (
    <div className={compact ? "card-body" : "card"} style={compact ? { borderBottom: "1px solid var(--z-sep)", fontSize: 12, color: "var(--z-body)" } : { marginBottom: 16, fontSize: 12, color: "var(--z-body)" }}>
      <div className="row" style={{ gap: 8, alignItems: "flex-start" }}>
        <span className="live-dot" style={{ marginTop: 5 }} />
        <span><strong style={{ color: "var(--z-dark)" }}>Recording is live.</strong> The first usage events land within a minute of someone using the app; there is no backfill from before recording began.</span>
      </div>
    </div>
  );
}

function UAStateCard({ state, compact }) {
  const [title, body] = UA_STATE_COPY[state.status] || UA_STATE_COPY.error;
  return (
    <div className={compact ? "card-body" : "card"} style={compact ? null : { marginBottom: 16 }}>
      <div className="row" style={{ gap: 8, alignItems: "flex-start" }}>
        {state.status === "loading" ? <span className="spinner" /> : <Icon name="info" size={14} style={{ flexShrink: 0, marginTop: 2 }} />}
        <div>
          <div style={{ fontWeight: 600, color: "var(--z-dark)", fontSize: 13 }}>{title}</div>
          {body ? <div style={{ fontSize: 12, color: "var(--z-body)", marginTop: 3, lineHeight: 1.5 }}>{body}</div> : null}
          {state.detail ? <div className="f-mono" style={{ fontSize: 10.5, color: "var(--z-muted)", marginTop: 4, wordBreak: "break-word" }}>{state.detail}</div> : null}
        </div>
      </div>
    </div>
  );
}

/* ── per-user drill drawer ──────────────────────────────────────── */
function UASessionRow({ s, open, onToggle }) {
  return (
    <div style={{ border: `1px solid ${open ? UA_FILL : "var(--z-sep)"}`, borderRadius: 8, marginBottom: 6, overflow: "hidden", background: "#fff" }}>
      <button onClick={onToggle} style={{ width: "100%", background: "none", border: 0, padding: "10px 12px", cursor: "pointer", textAlign: "left" }}>
        <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 7, flexWrap: "wrap" }}>
          <span style={{ fontSize: 12, fontWeight: 600, color: "var(--z-dark)" }}>{uaDate(s.start)} · {uaTime(s.start)}</span>
          {s.live ? <UAStatus status="Live" /> : null}
          <span className="spacer" />
          <span style={{ fontSize: 11, color: "var(--z-body)", fontVariantNumeric: "tabular-nums" }}>{uaDur(s.secs)} · {s.pages.filter(p => p.view).length} pages</span>
          <Icon name={open ? "chevron-u" : "chevron-d"} size={13} style={{ color: "var(--z-muted)" }} />
        </div>
        <div style={{ display: "flex", height: 8, borderRadius: 4, overflow: "hidden", gap: 1 }}>
          {s.pages.map((p, i) => <div key={i} title={`${p.label}${p.clientName ? " · " + p.clientName : ""} · ${uaDur(p.secs)}`} style={{ flex: Math.max(p.secs, 1), background: UA_PAGE_COLOR[p.key] || "#9AA9AA" }} />)}
        </div>
      </button>
      {open ? (
        <div style={{ padding: "2px 12px 10px" }}>
          {s.pages.map((p, i) => (
            <div key={i} style={{ display: "flex", alignItems: "center", gap: 8, padding: "5px 0", borderTop: i ? "1px dashed var(--z-sep)" : 0, fontSize: 11.5 }}>
              <span className="f-mono" style={{ width: 58, color: "var(--z-muted)", fontSize: 10.5 }}>{uaTime(p.at)}</span>
              <span style={{ width: 8, height: 8, borderRadius: 2, background: UA_PAGE_COLOR[p.key] || "#9AA9AA", flexShrink: 0 }} />
              <span style={{ color: "var(--z-dark)", fontWeight: 500 }}>{p.label}</span>
              {p.client ? <button className="chip" style={{ cursor: "pointer" }} onClick={() => navigate(`/clients/${p.client}/${UA_PAGES[p.key] && UA_PAGES[p.key].client ? p.key : "overview"}`)}>{p.clientName}</button> : null}
              <span className="spacer" />
              <span style={{ color: "var(--z-body)", fontVariantNumeric: "tabular-nums" }}>{p.now || (s.live && i === s.pages.length - 1 && !UA_LIVE()) ? "on page now" : uaDur(p.secs)}</span>
            </div>
          ))}
          <div style={{ fontSize: 10.5, color: "var(--z-muted)", marginTop: 6 }}>{s.id}{s.device ? ` · ${s.device}` : ""}{s.features.length ? ` · ${s.features.length} feature actions` : ""}</div>
        </div>
      ) : null}
    </div>
  );
}
function UAUserDrawer({ user, model, from, to, rangeLabel, onClose }) {
  const [openS, setOpenS] = useStateUA(0);
  const [limit, setLimit] = useStateUA(12);
  useEffectUA(() => { const k = e => { if (e.key === "Escape") onClose(); }; window.addEventListener("keydown", k); return () => window.removeEventListener("keydown", k); }, []);
  const agg = useMemoUA(() => uaAgg(model, from, to, user.email), [user.email, from.getTime(), model]);
  const list = agg.S.slice().reverse();
  const featTotal = Object.values(agg.feat).reduce((a, b) => a + b, 0);
  return ReactDOM.createPortal(
    <>
      <div className="drawer-mask" onClick={onClose} />
      <div className="drawer" style={{ width: 600 }}>
        <div className="drawer-head">
          <div style={{ width: 42, height: 42, borderRadius: "50%", background: UA_ROLE_COLOR[user.role], color: "#fff", display: "flex", alignItems: "center", justifyContent: "center", fontWeight: 700, flexShrink: 0 }}>{uaInitials(user.name)}</div>
          <div style={{ minWidth: 0, flex: 1 }}>
            <div className="title" style={{ display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap" }}>{user.name} <UAStatus status={user.status} /></div>
            <div className="sub f-mono">{user.email}</div>
            <div className="sub">{UA_ROLE_LABEL[user.role]}{user.team ? ` · ${user.team}` : ""} · last seen {uaRel(user.last, user.live, model.now)}</div>
          </div>
          <button className="btn btn-tertiary btn-sm close" onClick={onClose} aria-label="Close">✕</button>
        </div>
        <div className="drawer-body">
          <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: ".1em", color: "var(--z-muted)", textTransform: "uppercase", marginBottom: 8 }}>{rangeLabel}</div>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(4, minmax(0,1fr))", gap: 8, marginBottom: 16 }}>
            {[["Sessions", agg.sessions], ["Total time", uaDur(agg.secs)], ["Avg session", uaDur(agg.avg)], ["Page views", agg.views]].map(([l, v]) => (
              <div key={l} className="card-tile" style={{ padding: "9px 10px" }}><div style={{ fontSize: 9.5, color: "var(--z-muted)", textTransform: "uppercase", letterSpacing: ".05em" }}>{l}</div><div style={{ fontSize: 18, fontWeight: 400, color: "var(--z-dark)", marginTop: 2 }}>{v}</div></div>
            ))}
          </div>
          <div style={{ fontSize: 12, fontWeight: 600, color: "var(--z-dark)", marginBottom: 8 }}>Active time per day</div>
          <div style={{ marginBottom: 18 }}><UADailyChart daily={agg.daily} from={from} minutes /></div>
          <div style={{ fontSize: 12, fontWeight: 600, color: "var(--z-dark)", marginBottom: 8 }}>Where their time goes</div>
          <div style={{ marginBottom: 18 }}>
            {agg.pages.slice(0, 6).map(p => (
              <div key={p.key} style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 6, fontSize: 11.5 }}>
                <span style={{ width: 130, color: "var(--z-dark)" }} className="txt-fit-1">{p.label}</span>
                <div style={{ flex: 1, height: 7, background: "var(--z-sep)", borderRadius: 4, overflow: "hidden" }}><div style={{ width: `${agg.secs ? p.secs / agg.secs * 100 : 0}%`, height: "100%", background: UA_PAGE_COLOR[p.key] || "#9AA9AA" }} /></div>
                <span style={{ width: 64, textAlign: "right", color: "var(--z-body)", fontVariantNumeric: "tabular-nums" }}>{uaDur(p.secs)}</span>
              </div>
            ))}
            {!agg.pages.length ? <div style={{ fontSize: 12, color: "var(--z-muted)" }}>No activity in this period.</div> : null}
          </div>
          {agg.clients.length ? (
            <>
              <div style={{ fontSize: 12, fontWeight: 600, color: "var(--z-dark)", marginBottom: 8 }}>Clients researched</div>
              <div style={{ display: "flex", gap: 6, flexWrap: "wrap", marginBottom: 18 }}>
                {agg.clients.map(c => <button key={c.id} className="chip" style={{ cursor: "pointer" }} onClick={() => navigate(`/clients/${c.id}/overview`)} title={`${c.views} views`}>{c.name} · {uaDur(c.secs)}</button>)}
              </div>
            </>
          ) : null}
          {featTotal ? (
            <div style={{ display: "flex", gap: 6, flexWrap: "wrap", marginBottom: 18 }}>
              {uaFeatures().filter(([k]) => agg.feat[k]).map(([k, l]) => <span key={k} className="b b-purple">{l} · {agg.feat[k]}</span>)}
            </div>
          ) : null}
          <div style={{ fontSize: 12, fontWeight: 600, color: "var(--z-dark)", marginBottom: 8 }}>Sessions <span style={{ color: "var(--z-muted)", fontWeight: 400 }}>· click to see the page-by-page path</span></div>
          {list.slice(0, limit).map((s, i) => <UASessionRow key={s.id} s={s} open={openS === i} onToggle={() => setOpenS(o => o === i ? -1 : i)} />)}
          {list.length > limit ? <button className="btn btn-tertiary btn-sm" onClick={() => setLimit(l => l + 12)}>Show {Math.min(12, list.length - limit)} more of {list.length - limit}</button> : null}
        </div>
        <div className="drawer-foot">
          <button className="btn btn-tertiary" onClick={() => uaCsv(agg.S, `dma-usage-${user.email.split("@")[0]}.csv`)}><Icon name="download" size={13} /> Export CSV</button>
          <button className="btn btn-secondary" onClick={onClose}>Close</button>
        </div>
      </div>
    </>,
    document.body
  );
}

/* ── page ───────────────────────────────────────────────────────── */
function UsagePage() {
  const { role, pushToast } = useApp();
  const [range, setRange] = useStateUA(30);
  const [q, setQ] = useStateUA("");
  const [roleF, setRoleF] = useStateUA("ALL");
  const [statusF, setStatusF] = useStateUA("ALL");
  const [sort, setSort] = useStateUA({ k: "last", dir: -1 });
  const [userOpen, setUserOpen] = useStateUA(null);
  const all = useUsageModel(range);
  const ok = all.status === "ok";
  const bounds = useMemoUA(() => ok ? uaDayBounds(all.now, range) : null, [ok, all, range]);
  // The filter bar at the top decides WHO the whole page is about (owner,
  // 2026-10-08: "the filter should be on top and all bottom components should
  // adjust accordingly"). Status is read from everyone's own activity, then
  // the model is narrowed to the matching people, and every card below —
  // KPIs, signals, the chart, live now, pages, clients, the hour heatmap and
  // the user table — is computed from that narrowed model.
  const allRows = useMemoUA(() => ok ? uaRows(all, uaAgg(all, bounds.from, bounds.to), bounds.to) : [], [ok, all, bounds]);
  const filtering = roleF !== "ALL" || statusF !== "ALL" || !!q.trim();
  const keep = useMemoUA(() => {
    const needle = q.trim().toLowerCase();
    return new Set(allRows.filter(r => (roleF === "ALL" || r.role === roleF) && (statusF === "ALL" || r.status === statusF)
      && (!needle || (r.name + " " + r.email + " " + (r.team || "")).toLowerCase().includes(needle))).map(r => r.email));
  }, [allRows, roleF, statusF, q]);
  const model = useMemoUA(() => !ok || !filtering ? all : uaNarrow(all, keep), [ok, all, filtering, keep]);
  const cur = useMemoUA(() => ok ? uaAgg(model, bounds.from, bounds.to) : null, [ok, model, bounds]);
  const prevFrom = bounds ? new Date(bounds.from.getTime() - range * UA_DAY) : null;
  const prevOk = ok && uaPrevCovered(model, prevFrom);
  const prev = useMemoUA(() => prevOk ? uaAgg(model, prevFrom, bounds.from) : null, [prevOk, model, bounds]);
  const rows = useMemoUA(() => ok ? uaRows(model, cur, bounds.to) : [], [ok, model, cur]);
  const linkRows = useMemoUA(() => ok ? uaLinkRows(model, bounds.from, bounds.to) : [], [ok, model, bounds]);

  if (role !== "ADMIN") return <PageShell title="Usage analytics"><div className="empty"><div className="icon"><Icon name="lock" size={22} /></div><h3>Admin access required</h3><p>Switch to the Admin role to view usage analytics.</p></div></PageShell>;

  const rangeLabel = `Last ${range} days`;
  const head = (
    <div className="page-head" data-screen-label="Admin · Usage analytics">
      <div>
        <div className="eyebrow">Settings &amp; operations</div>
        <h1>Usage analytics</h1>
        <div className="sub">Who uses DMA Insights, which pages they use, and how long they stay · {rangeLabel.toLowerCase()}
          {ok && all.recordingSince && all.recordingSince > bounds.from ? ` · recording since ${uaDate(all.recordingSince)}` : ""}</div>
      </div>
      <div className="actions">
        <div className="toggle-row">{[7, 30, 90].map(r => <button key={r} className={range === r ? "on" : ""} onClick={() => setRange(r)}>{r}d</button>)}</div>
        <button className="btn btn-tertiary" disabled={!ok || !cur.sessions} onClick={() => { uaCsv(cur.S, `dma-usage-last-${range}d.csv`); pushToast(`Exported ${cur.views} page views · ${cur.sessions} sessions`, "success"); }}><Icon name="download" size={13} /> Export CSV</button>
      </div>
    </div>
  );
  if (!ok) return <PageShell title="Usage analytics" crumbs={[{ label: "Admin", href: "/admin" }, { label: "Usage analytics" }]}>{head}<UAStateCard state={all} /></PageShell>;

  const shown = rows.slice()
    .sort((a, b) => { const k = sort.k; const av = k === "last" ? (a.last ? +a.last : 0) : a[k], bv = k === "last" ? (b.last ? +b.last : 0) : b[k]; return (typeof av === "string" ? av.localeCompare(bv) : av - bv) * sort.dir; });
  const SortTh = ({ k, children, right, cls }) => <th className={cls} style={{ textAlign: right ? "right" : "left", cursor: "pointer", userSelect: "none", whiteSpace: "nowrap" }} onClick={() => setSort(s => ({ k, dir: s.k === k ? -s.dir : (k === "name" ? 1 : -1) }))}>{children}{sort.k === k ? (sort.dir > 0 ? " ▲" : " ▼") : ""}</th>;

  const live = model.sessions.filter(s => s.live);
  // A nudge is for colleagues; a client who has not opened their link is
  // the Client links signal's business, not an email from this page.
  const atRisk = rows.filter(r => r.role !== "CLIENT" && (r.status === "Idle" || r.status === "Dormant"));
  const madeLinks = linkRows.filter(l => l.created);
  const recips = new Set(madeLinks.flatMap(l => l.recipients));
  const openedRecips = new Set(madeLinks.flatMap(l => l.recipients.filter(e => l.everOpened.has(e))));
  const clientReaders = new Set(linkRows.flatMap(l => [...l.readers]));
  const hasClients = allRows.some(r => r.role === "CLIENT") || (all.links || []).length > 0;
  const sticky = cur.pages.filter(p => p.views).slice().sort((a, b) => b.secs / b.views - a.secs / a.views)[0];
  let peak = null; cur.heat.forEach((row, d) => row.forEach((v, h) => { if (v && (!peak || v > peak[2])) peak = [d, h, v]; }));
  const DAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];
  const fmtH = h => `${h % 12 === 0 ? 12 : h % 12}${h >= 12 && h < 24 ? "pm" : "am"}`;
  const feats = uaFeatures();
  const featMax = Math.max(0, ...feats.map(([k]) => cur.feat[k] || 0));
  const respGrid = min => ({ display: "grid", gridTemplateColumns: `repeat(auto-fit, minmax(min(100%, ${min}px), 1fr))`, gap: 16, marginBottom: 16 });
  const showTeam = allRows.some(r => r.team);
  const who = filtering ? `${keep.size} of ${allRows.length} ${allRows.length === 1 ? "person" : "people"}` : null;
  const clear = () => { setQ(""); setRoleF("ALL"); setStatusF("ALL"); };
  const mailto = atRisk.length ? `mailto:${atRisk.map(r => r.email).join(",")}?subject=${encodeURIComponent("DMA Insights")}` : null;

  return (
    <PageShell title="Usage analytics" crumbs={[{ label: "Admin", href: "/admin" }, { label: "Usage analytics" }]}>
      {head}
      <div className="card ua-filters" data-screen-label="Usage filters">
        <Icon name="filter" size={13} style={{ color: "var(--z-muted)", flexShrink: 0 }} />
        <input className="inp inp-sm" aria-label="Search people" placeholder={hasClients ? "Search name, email or client" : "Search name or email"} value={q} onChange={e => setQ(e.target.value)} style={{ flex: "1 1 220px", minWidth: 0 }} />
        <select className="inp inp-sm" aria-label="Role" value={roleF} onChange={e => setRoleF(e.target.value)} style={{ flex: "0 1 140px" }}><option value="ALL">All roles</option><option value="AE">AE</option><option value="ANALYST">Analyst</option><option value="ADMIN">Admin</option><option value="CLIENT">Client (link)</option></select>
        <select className="inp inp-sm" aria-label="Status" value={statusF} onChange={e => setStatusF(e.target.value)} style={{ flex: "0 1 150px" }}><option value="ALL">All statuses</option><option>Live</option><option>Active</option><option>Idle</option><option>Dormant</option><option value="Never">No activity yet</option></select>
        {filtering ? <><span className="b b-teal b-token">{who}</span><button className="btn btn-tertiary btn-sm" onClick={clear}>Clear</button></> : null}
      </div>
      {all.awaiting ? <UAAwaiting /> : null}
      {all.truncated ? <div className="card" style={{ marginBottom: 16, fontSize: 12, color: "var(--z-org)" }}>This range holds more events than one read returns; the oldest are not shown. Choose a shorter range.</div> : null}

      {/* KPIs */}
      <div style={{ ...respGrid(170), gap: 12 }}>
        <UAKpi label="Active users" value={cur.users.size} cur={cur.users.size} prev={prev && prev.users.size} />
        <UAKpi label="Sessions" value={cur.sessions} cur={cur.sessions} prev={prev && prev.sessions} />
        <UAKpi label="Avg session" value={uaDur(cur.avg)} cur={cur.avg} prev={prev && prev.avg} />
        <UAKpi label="Total active time" value={uaDur(cur.secs)} cur={cur.secs} prev={prev && prev.secs} />
        <UAKpi label="Pages / session" value={cur.pps.toFixed(1)} cur={cur.pps} prev={prev && prev.pps} />
      </div>

      {/* Signals, computed from the data above */}
      <div className="card" style={{ marginBottom: 16, display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 230px), 1fr))", gap: 14 }}>
        {[
          ["Adoption", prev ? `${cur.users.size} people used DMA Insights ${rangeLabel.toLowerCase()} (${cur.users.size - prev.users.size >= 0 ? "+" : ""}${cur.users.size - prev.users.size} vs the prior period).`
                            : `${cur.users.size} ${cur.users.size === 1 ? "person" : "people"} used DMA Insights ${rangeLabel.toLowerCase()}.`, null],
          ["Stickiest surface", sticky ? `${sticky.label} holds attention longest — ${uaDur(sticky.secs / sticky.views)} per visit.` : "No page views recorded in this period.", null],
          ["Peak usage", peak ? `${DAYS[peak[0]]}s around ${fmtH(peak[1])}–${fmtH(peak[1] + 1)}. Schedule releases outside this window.` : "No page views recorded in this period.", null],
          ["Client links", madeLinks.length || clientReaders.size
            ? `${madeLinks.length} ${madeLinks.length === 1 ? "link" : "links"} generated ${rangeLabel.toLowerCase()}${recips.size ? ` · ${openedRecips.size} of ${recips.size} ${recips.size === 1 ? "recipient has" : "recipients have"} opened` : ""} · ${clientReaders.size} client ${clientReaders.size === 1 ? "reader" : "readers"} in the period.`
            : "No client links generated or opened in this period.", null],
          ["Needs a nudge", atRisk.length ? `${atRisk.map(r => r.name.split(" ")[0]).join(", ")} ${atRisk.length === 1 ? "hasn't" : "haven't"} been active in 7+ days.` : "Everyone seen has been active this week.", mailto],
        ].map(([t, body, href]) => (
          <div key={t}>
            <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: ".1em", color: "var(--z-mid)", textTransform: "uppercase", marginBottom: 4 }}>{t}</div>
            <div style={{ fontSize: 12.5, color: "var(--z-body)", lineHeight: 1.5 }}>{body}</div>
            {href ? <a className="btn btn-tertiary btn-sm" style={{ marginTop: 6, paddingLeft: 0 }} href={href}>Email them <Icon name="arrow-r" size={11} /></a> : null}
          </div>
        ))}
      </div>

      {/* Activity + Live */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 340px), 1fr))", gap: 16, marginBottom: 16 }}>
        <div className="card" style={{ gridColumn: "span 2" }}>
          <div className="row" style={{ marginBottom: 14, flexWrap: "wrap", gap: 8 }}>
            <h3 style={{ margin: 0, fontSize: 13 }}>Daily activity</h3>
            <span style={{ fontSize: 11, color: "var(--z-muted)" }}>sessions per day, by role</span>
            <span className="spacer" />
            <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>{Object.entries(UA_ROLE_COLOR).filter(([r]) => roleF === "ALL" || r === roleF).map(([r, c]) => <span key={r} style={{ display: "inline-flex", gap: 5, alignItems: "center", fontSize: 11, color: "var(--z-body)", whiteSpace: "nowrap" }}><span style={{ width: 9, height: 9, borderRadius: 2, background: c }} />{UA_ROLE_LABEL[r]}</span>)}</div>
          </div>
          <UADailyChart daily={cur.daily} from={bounds.from} />
        </div>
        <div className="card">
          <div className="row" style={{ marginBottom: 12 }}><h3 style={{ margin: 0, fontSize: 13 }}>Live now</h3><span className="b b-teal b-token" style={{ display: "inline-flex", gap: 4 }}><span className="live-dot" /> {live.length}</span></div>
          {live.length ? live.map(s => { const u = rows.find(r => r.email === s.email) || { name: uaNameOf(s.email), role: s.role, email: s.email }; const p = s.pages[s.pages.length - 1]; return (
            <button key={s.id} onClick={() => setUserOpen(u.email)} style={{ display: "flex", width: "100%", gap: 10, alignItems: "center", padding: "8px 0", background: "none", border: 0, borderTop: "1px solid var(--z-sep)", cursor: "pointer", textAlign: "left" }}>
              <span style={{ width: 30, height: 30, borderRadius: "50%", background: UA_ROLE_COLOR[u.role], color: "#fff", fontSize: 11, fontWeight: 700, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>{uaInitials(u.name)}</span>
              <span style={{ flex: 1, minWidth: 0 }}><span style={{ display: "block", fontSize: 12.5, fontWeight: 600, color: "var(--z-dark)" }}>{u.name}</span><span style={{ display: "block", fontSize: 11, color: "var(--z-muted)" }} className="txt-fit-1">{p ? `On ${p.label}${p.clientName ? ` · ${p.clientName}` : ""}` : "Active now"}</span></span>
              <span style={{ fontSize: 11, color: "var(--z-body)", fontVariantNumeric: "tabular-nums" }}>{uaDur((model.now - s.start) / 1000)}</span>
            </button>
          ); }) : <div style={{ fontSize: 12, color: "var(--z-muted)", borderTop: "1px solid var(--z-sep)", paddingTop: 8 }}>Nobody is active right now.</div>}
          <div style={{ fontSize: 12, fontWeight: 600, color: "var(--z-dark)", margin: "14px 0 8px" }}>Feature adoption</div>
          {feats.map(([k, l]) => { const v = cur.feat[k] || 0; return (
            <div key={k} style={{ marginBottom: 7 }}>
              <div style={{ display: "flex", fontSize: 11.5, marginBottom: 3 }}><span style={{ color: "var(--z-body)" }}>{l}</span><span className="spacer" /><span style={{ color: "var(--z-dark)", fontWeight: 600, fontVariantNumeric: "tabular-nums" }}>{v}</span></div>
              <div style={{ height: 5, background: "var(--z-sep)", borderRadius: 3, overflow: "hidden" }}><div style={{ width: `${featMax ? v / featMax * 100 : 0}%`, height: "100%", background: "var(--z-dpur)" }} /></div>
            </div>
          ); })}
        </div>
      </div>

      {/* Pages + heatmap */}
      <div style={respGrid(420)}>
        <div className="card flush">
          <div className="card-head"><h3>Pages · where time is spent</h3><span style={{ fontSize: 11, color: "var(--z-muted)" }}>{cur.views} views</span></div>
          <div style={{ overflowX: "auto" }}>
            <table className="tbl">
              <thead><tr><th>Page</th><th style={{ textAlign: "right" }}>Views</th><th style={{ textAlign: "right" }}>Users</th><th style={{ textAlign: "right" }}>Avg time</th><th style={{ width: 150 }}>Share of time</th></tr></thead>
              <tbody>
                {cur.pages.map(p => (
                  <tr key={p.key}>
                    <td data-label="Page"><span style={{ display: "inline-flex", gap: 7, alignItems: "center" }}><span style={{ width: 8, height: 8, borderRadius: 2, background: UA_PAGE_COLOR[p.key] || "#9AA9AA" }} />{p.label}</span></td>
                    <td data-label="Views" style={{ textAlign: "right", fontVariantNumeric: "tabular-nums" }}>{p.views}</td>
                    <td data-label="Users" style={{ textAlign: "right" }}>{p.users.size}</td>
                    <td data-label="Avg time" style={{ textAlign: "right", fontVariantNumeric: "tabular-nums" }}>{p.views ? uaDur(p.secs / p.views) : "No views"}</td>
                    <td data-label="Share"><div style={{ display: "flex", alignItems: "center", gap: 6 }}><div style={{ flex: 1, height: 6, background: "var(--z-sep)", borderRadius: 3, overflow: "hidden" }}><div style={{ width: `${cur.secs ? p.secs / cur.secs * 100 : 0}%`, height: "100%", background: UA_PAGE_COLOR[p.key] || "#9AA9AA" }} /></div><span style={{ fontSize: 10.5, color: "var(--z-muted)", width: 30, textAlign: "right" }}>{cur.secs ? Math.round(p.secs / cur.secs * 100) : 0}%</span></div></td>
                  </tr>
                ))}
                {!cur.pages.length ? <tr><td colSpan={5} style={{ textAlign: "center", color: "var(--z-muted)", padding: 20 }}>No page views recorded in this period.</td></tr> : null}
              </tbody>
            </table>
          </div>
        </div>
        <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
          <div className="card">
            <div className="row" style={{ marginBottom: 12 }}><h3 style={{ margin: 0, fontSize: 13 }}>When people use it</h3><span className="spacer" /><span style={{ fontSize: 11, color: "var(--z-muted)" }}>page views by hour</span></div>
            <UAHourHeat heat={cur.heat} />
          </div>
          <div className="card">
            <div className="row" style={{ marginBottom: 10 }}><h3 style={{ margin: 0, fontSize: 13 }}>Most-researched clients</h3></div>
            {cur.clients.slice(0, 6).map(c => (
              <button key={c.id} onClick={() => navigate(`/clients/${c.id}/overview`)} style={{ display: "flex", width: "100%", alignItems: "center", gap: 8, padding: "6px 0", background: "none", border: 0, cursor: "pointer", textAlign: "left", fontSize: 12 }}>
                <span style={{ width: 150, color: "var(--z-dark)", fontWeight: 500 }} className="txt-fit-1">{c.name}</span>
                <div style={{ flex: 1, height: 6, background: "var(--z-sep)", borderRadius: 3, overflow: "hidden" }}><div style={{ width: `${cur.clients[0].secs ? c.secs / cur.clients[0].secs * 100 : 0}%`, height: "100%", background: UA_FILL }} /></div>
                <span style={{ fontSize: 11, color: "var(--z-muted)", width: 110, textAlign: "right" }}>{c.users.size} {c.users.size === 1 ? "user" : "users"} · {uaDur(c.secs)}</span>
              </button>
            ))}
            {!cur.clients.length ? <div style={{ fontSize: 12, color: "var(--z-muted)" }}>No client pages viewed in this period.</div> : null}
          </div>
        </div>
      </div>

      {/* Client links: every link generated, who it went to, who opened it */}
      {roleF === "ALL" || roleF === "CLIENT" || linkRows.length ? (
      <div className="card flush" style={{ marginBottom: 16 }} data-screen-label="Usage · Client links">
        <div className="card-head" style={{ flexWrap: "wrap", gap: 8 }}>
          <div className="row"><Icon name="share" size={14} /><h3>Client links · generated &amp; opened</h3></div>
          <span className="spacer" />
          <span style={{ fontSize: 11, color: "var(--z-muted)" }}>{madeLinks.length} generated · {clientReaders.size} {clientReaders.size === 1 ? "reader" : "readers"} · {rangeLabel.toLowerCase()}</span>
        </div>
        <div className="tbl-reflow reflow-early">
          <table className="tbl">
            <thead><tr>
              <th>Client</th><th>Shared by</th><th className="col-drop2" style={{ whiteSpace: "nowrap" }}>Created</th><th>Recipients</th>
              <th style={{ textAlign: "right" }}>Opens</th><th className="col-drop2" style={{ textAlign: "right" }}>Views</th><th style={{ textAlign: "right", whiteSpace: "nowrap" }}>Read time</th>
              <th className="col-drop" style={{ whiteSpace: "nowrap" }}>Last opened</th><th className="col-drop" style={{ textAlign: "right" }}>Refused</th>
            </tr></thead>
            <tbody>
              {linkRows.map(l => (
                <tr key={l.jti}>
                  <td data-label="Client"><div style={{ fontWeight: 600, color: "var(--z-dark)" }}>{l.clientName || l.client || "Unknown client"}</div>{l.expires ? <div style={{ fontSize: 10.5, color: l.expires < model.now ? "var(--z-org)" : "var(--z-muted)" }}>{l.expires < model.now ? "Expired" : "Expires"} {uaDate(l.expires)}</div> : null}</td>
                  <td data-label="Shared by">{l.by ? <><div>{uaNameOf(l.by)}</div><div className="f-mono t-email" style={{ fontSize: 10, color: "var(--z-muted)" }}>{l.by}</div></> : <span style={{ color: "var(--z-muted)" }}>Before recording</span>}</td>
                  <td data-label="Created" className="col-drop2" style={{ whiteSpace: "nowrap" }}>{l.at ? uaDate(l.at) : "Before recording"}</td>
                  <td data-label="Recipients">
                    {l.recipients.length ? l.recipients.map(e => (
                      <button key={e} className="f-mono t-email" onClick={() => setUserOpen(e)} title={l.everOpened.has(e) ? "Opened" : "Not opened yet"} style={{ display: "block", background: "none", border: 0, padding: 0, cursor: "pointer", textAlign: "left", fontSize: 10.5, color: l.everOpened.has(e) ? "var(--z-dark)" : "var(--z-muted)" }}>{l.everOpened.has(e) ? "● " : "○ "}{e}</button>
                    )) : <span style={{ color: "var(--z-muted)" }}>Not recorded</span>}
                    {l.domains.length ? <div style={{ fontSize: 10, color: "var(--z-muted)" }}>Domains: {l.domains.join(", ")}</div> : null}
                    {[...l.readers].filter(e => !l.recipients.includes(e)).map(e => <button key={e} className="f-mono t-email" onClick={() => setUserOpen(e)} title="Admitted by domain" style={{ display: "block", background: "none", border: 0, padding: 0, cursor: "pointer", textAlign: "left", fontSize: 10.5, color: "var(--z-dark)" }}>● {e}</button>)}
                  </td>
                  <td data-label="Opens" style={{ textAlign: "right", fontVariantNumeric: "tabular-nums" }}>{l.opens}</td>
                  <td data-label="Views" className="col-drop2" style={{ textAlign: "right", fontVariantNumeric: "tabular-nums" }}>{l.views}</td>
                  <td data-label="Read time" style={{ textAlign: "right", fontVariantNumeric: "tabular-nums", whiteSpace: "nowrap" }}>{l.secs ? uaDur(l.secs) : "None yet"}</td>
                  <td data-label="Last opened" className="col-drop" style={{ whiteSpace: "nowrap" }}>{l.last ? uaRel(l.last, false, model.now) : "Never"}</td>
                  <td data-label="Refused" className="col-drop" style={{ textAlign: "right", fontVariantNumeric: "tabular-nums", color: l.refused ? "var(--z-org)" : undefined }}>{l.refused}</td>
                </tr>
              ))}
              {!linkRows.length ? <tr><td colSpan={9} className="tbl-empty">No client links generated or opened in this period.</td></tr> : null}
            </tbody>
          </table>
        </div>
      </div>
      ) : null}

      {/* Users */}
      <div className="card flush">
        <div className="card-head" style={{ flexWrap: "wrap", gap: 8 }}>
          <h3>Users · activity &amp; time spent</h3>
          <span className="spacer" />
          <span style={{ fontSize: 11, color: "var(--z-muted)" }}>{who || `${allRows.length} ${allRows.length === 1 ? "person" : "people"}`}</span>
        </div>
        <div className="tbl-reflow reflow-early">
          <table className="tbl">
            <thead><tr>
              <SortTh k="name">User</SortTh><th>Role</th><th>Status</th><SortTh k="last">Last seen</SortTh>
              <SortTh k="sessions" right cls="col-drop2">Sessions</SortTh><SortTh k="secs" right>Total time</SortTh><th className="col-drop" style={{ textAlign: "right", whiteSpace: "nowrap" }}>Avg session</th>
              <th className="col-drop">Top page</th><th className="col-drop" style={{ whiteSpace: "nowrap" }}>Last 14 days</th><th></th>
            </tr></thead>
            <tbody>
              {shown.map(r => (
                <tr key={r.email} onClick={() => setUserOpen(r.email)} style={{ cursor: "pointer" }}>
                  <td data-label="User"><div style={{ fontWeight: 600, color: "var(--z-dark)" }}>{r.name}</div><div className="f-mono t-email" style={{ fontSize: 10, color: "var(--z-muted)" }}>{r.email}</div>{r.team ? <div style={{ fontSize: 10.5, color: "var(--z-muted)" }}>{r.team}</div> : null}</td>
                  <td data-label="Role"><span className="b b-token" style={{ background: UA_ROLE_COLOR[r.role] + "22", color: UA_ROLE_COLOR[r.role] }}>{UA_ROLE_LABEL[r.role]}</span></td>
                  <td data-label="Status"><UAStatus status={r.status} /></td>
                  <td data-label="Last seen" style={{ whiteSpace: "nowrap" }}>{uaRel(r.last, r.live, model.now)}</td>
                  <td data-label="Sessions" className="col-drop2" style={{ textAlign: "right", fontVariantNumeric: "tabular-nums" }}>{r.sessions}</td>
                  <td data-label="Total time" style={{ textAlign: "right", fontVariantNumeric: "tabular-nums" }}>{uaDur(r.secs)}</td>
                  <td data-label="Avg session" className="col-drop" style={{ textAlign: "right", fontVariantNumeric: "tabular-nums", whiteSpace: "nowrap" }}>{r.sessions ? uaDur(r.avg) : "No sessions"}</td>
                  <td data-label="Top page" className="col-drop" style={{ fontSize: 11.5 }}>{r.top}</td>
                  <td data-label="Last 14 days" className="col-drop"><UASpark vals={r.spark} color={UA_ROLE_COLOR[r.role]} /></td>
                  <td style={{ textAlign: "right" }}><Icon name="chevron-r" size={13} style={{ color: "var(--z-muted)" }} /></td>
                </tr>
              ))}
              {!shown.length ? <tr><td colSpan={10} className="tbl-empty">No users match these filters.</td></tr> : null}
            </tbody>
          </table>
        </div>
      </div>

      {userOpen ? <UAUserDrawer user={rows.find(r => r.email === userOpen) || { email: userOpen, name: uaNameOf(userOpen), role: "AE", status: "Never", last: null }} model={model} from={bounds.from} to={bounds.to} rangeLabel={rangeLabel} onClose={() => setUserOpen(null)} /> : null}
    </PageShell>
  );
}

/* ── Admin home: usage at a glance (last 7 days, links to full analytics) ── */
function UsageGlanceCard() {
  const model = useUsageModel(7);
  const ok = model.status === "ok";
  const g = useMemoUA(() => {
    if (!ok) return null;
    const { from, to } = uaDayBounds(model.now, 7);
    const prevFrom = new Date(from.getTime() - 7 * UA_DAY);
    const cur = uaAgg(model, from, to);
    const prev = uaPrevCovered(model, prevFrom) ? uaAgg(model, prevFrom, from) : null;
    const trend = uaAgg(model, new Date(to.getTime() - 14 * UA_DAY), to);
    const quiet = model.people.filter(u => { const l = model.lastSeen[u.email]; return u.role !== "CLIENT" && l && (model.now - l) / UA_DAY >= 7; });
    return { cur, prev, trend, quiet, to, live: model.sessions.filter(s => s.live) };
  }, [ok, model]);
  const header = (liveCount) => (
    <div className="card-head" style={{ flexWrap: "wrap", gap: 8 }}>
      <div className="row"><Icon name="users" size={14} /><h3>Usage · last 7 days</h3></div>
      {liveCount != null ? <span className="b b-teal b-token" style={{ display: "inline-flex", gap: 4, alignItems: "center" }}><span className="live-dot" /> {liveCount} live now</span> : null}
      <span className="spacer" />
      <button className="btn btn-tertiary btn-sm" onClick={() => navigate("/admin/usage")}>Open usage analytics <Icon name="arrow-r" size={11} /></button>
    </div>
  );
  if (!ok) return <div className="card flush" style={{ marginBottom: 16 }} data-screen-label="Admin · Usage at a glance">{header(null)}<UAStateCard state={model} compact /></div>;
  const { cur, prev, trend, quiet, live, to } = g;
  const pct = (a, b) => prev && b ? Math.round((a - b) / b * 100) : null;
  const kpis = [
    ["Active users", cur.users.size, pct(cur.users.size, prev && prev.users.size)],
    ["Sessions", cur.sessions, pct(cur.sessions, prev && prev.sessions)],
    ["Avg session", uaDur(cur.avg), pct(cur.avg, prev && prev.avg)],
    ["Active time", uaDur(cur.secs), pct(cur.secs, prev && prev.secs)],
  ];
  const vals = trend.daily.map(d => d.AE + d.ANALYST + d.ADMIN + (d.CLIENT || 0)), max = Math.max(1, ...vals);
  const name = em => (model.people.find(u => u.email === em) || {}).name || uaNameOf(em);
  return (
    <div className="card flush" style={{ marginBottom: 16 }} data-screen-label="Admin · Usage at a glance">
      {header(live.length)}
      {model.awaiting ? <UAAwaiting compact /> : null}
      <div className="card-body">
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 150px), 1fr))", gap: 10, marginBottom: 16 }}>
          {kpis.map(([l, v, d]) => (
            <button key={l} className="card-tile clickable" onClick={() => navigate("/admin/usage")} style={{ padding: "10px 12px", textAlign: "left" }}>
              <div style={{ fontSize: 10, color: "var(--z-muted)", textTransform: "uppercase", letterSpacing: ".06em", fontWeight: 600 }}>{l}</div>
              <div style={{ fontSize: 22, fontWeight: 300, color: "var(--z-dark)", marginTop: 2, fontVariantNumeric: "tabular-nums" }}>{v}</div>
              {d != null
                ? <div style={{ fontSize: 10.5, color: d >= 0 ? "var(--z-mid)" : "var(--z-org)", fontWeight: 600 }}>{d >= 0 ? "▲" : "▼"} {Math.abs(d)}% <span style={{ color: "var(--z-muted)", fontWeight: 400 }}>vs prior week</span></div>
                : <div style={{ fontSize: 10.5, color: "var(--z-muted)" }}>no prior week recorded</div>}
            </button>
          ))}
        </div>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 240px), 1fr))", gap: 18 }}>
          <div>
            <div style={{ fontSize: 11, fontWeight: 600, color: "var(--z-dark)", marginBottom: 8 }}>Sessions · last 14 days</div>
            <div style={{ display: "flex", alignItems: "flex-end", gap: 3, height: 64 }}>
              {trend.daily.map((d, i) => <div key={i} title={`${uaDate(new Date(to.getTime() - (14 - i) * UA_DAY))} · ${vals[i]} sessions`} style={{ flex: 1, height: `${Math.max(vals[i] ? 6 : 3, vals[i] / max * 100)}%`, background: i >= 7 ? UA_FILL : "var(--z-sep)", borderRadius: 2 }} />)}
            </div>
            <div style={{ display: "flex", justifyContent: "space-between", fontSize: 9.5, color: "var(--z-muted)", marginTop: 4 }}><span>Prior week</span><span>This week</span></div>
          </div>
          <div>
            <div style={{ fontSize: 11, fontWeight: 600, color: "var(--z-dark)", marginBottom: 8 }}>Top pages by time</div>
            {cur.pages.slice(0, 4).map(p => (
              <div key={p.key} style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 6, fontSize: 11.5 }}>
                <span style={{ width: 8, height: 8, borderRadius: 2, background: UA_PAGE_COLOR[p.key] || "#9AA9AA", flexShrink: 0 }} />
                <span style={{ flex: 1, minWidth: 0, color: "var(--z-dark)" }} className="txt-fit-1">{p.label}</span>
                <span style={{ color: "var(--z-muted)", fontVariantNumeric: "tabular-nums" }}>{uaDur(p.secs)}</span>
              </div>
            ))}
            {!cur.pages.length ? <div style={{ fontSize: 11.5, color: "var(--z-muted)" }}>No page views recorded this week.</div> : null}
          </div>
          <div>
            <div style={{ fontSize: 11, fontWeight: 600, color: "var(--z-dark)", marginBottom: 8 }}>Live now</div>
            {live.map(s => { const p = s.pages[s.pages.length - 1]; return (
              <div key={s.id} style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 6, fontSize: 11.5 }}>
                <span style={{ width: 22, height: 22, borderRadius: "50%", background: UA_ROLE_COLOR[s.role], color: "#fff", fontSize: 9, fontWeight: 700, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>{uaInitials(name(s.email))}</span>
                <span style={{ flex: 1, minWidth: 0 }} className="txt-fit-1"><strong style={{ color: "var(--z-dark)", fontWeight: 600 }}>{name(s.email).split(" ")[0]}</strong> <span style={{ color: "var(--z-muted)" }}>{p ? `· ${p.label.replace("Client · ", "")}${p.clientName ? ` · ${p.clientName}` : ""}` : ""}</span></span>
              </div>
            ); })}
            {!live.length ? <div style={{ fontSize: 11.5, color: "var(--z-muted)" }}>Nobody is active right now.</div> : null}
            {quiet.length ? (
              <div style={{ marginTop: 10, padding: "8px 10px", background: "rgba(214,109,42,.08)", borderRadius: 6, fontSize: 11.5, color: "var(--z-body)" }}>
                <strong style={{ color: "var(--z-org)" }}>{quiet.length} inactive 7+ days · </strong>{quiet.map(u => u.name.split(" ")[0]).join(", ")}
              </div>
            ) : null}
          </div>
        </div>
      </div>
    </div>
  );
}

Object.assign(window, { UsagePage, UsageGlanceCard, useUsageModel, uaModelFromWire, uaAgg, uaRows, uaLinkRows, uaNarrow, uaDayBounds, uaPrevCovered, uaRel });
