"""
color_level_system.py — THE single source of truth for the DMA First Call Deck skill.

Every editor and QA script MUST import from this module. Hand-maintained tables in
SKILL.md, brand_guidelines.md, and editing_contract.md are GENERATED from this file
by scripts/utils/generate_color_docs.py — do not edit those tables directly.

This module defines:
  1. Level palettes (4-tier heatmap/Slide 10; 5-tier Slide 13)
  2. Static colors (Zennify brand accents, legend strips, structural tints)
  3. Theme references (shapes that deliberately use schemeClr for theme adaptation)
  4. Per-slide role catalogues — for every edited shape on every edited slide,
     describe what content type it is, where the content comes from, and which
     of {fill, border, text, text_color} are written.
  5. Score-to-level functions and a uniform `get_expected_hex` helper used by
     both editors (to decide what to write) and QA (to verify what was written).

Every value in this module has been verified against the credit_unions template
uploaded by the skill owner on 2026-04-17. Template scans are stored in
`template_ground_truth.json` adjacent to this file (generated by
scripts/utils/scan_template.py).

Content-type taxonomy (used by per-slide role catalogues):
  - "data":      color derived from an input score + a palette key
  - "static":    color fixed across all decks (brand accent, structural tint, etc.)
  - "theme_ref": shape uses <a:schemeClr> deliberately; editors must NOT override
                 with <a:srgbClr> because the theme resolves correctly per context
  - "text":      shape has its text replaced; no color operation
  - "image":     shape is an image replacement (radar chart, client logo)
"""

# ══════════════════════════════════════════════════════════════════════════════
# 1. LEVEL PALETTES
# ══════════════════════════════════════════════════════════════════════════════

LEVEL_4TIER = {
    "Activating": {
        "score_range": (0.00, 1.49),
        "accent":     "F97316",  # strip fill, progress bar fill/border, heatmap bar
        "card_bg":    "FFF3E8",  # heatmap bg_card fill/border, Slide 10 rec card bg
        "label_text": "F97316",  # level-label text color (verified on template)
    },
    "Building": {
        "score_range": (1.50, 2.49),
        "accent":     "8094C0",
        "card_bg":    "F2F4F9",
        "label_text": "4E5E8A",
    },
    "Competing": {
        "score_range": (2.50, 3.49),
        "accent":     "27BBAF",
        "card_bg":    "E6F5F3",
        "label_text": "198478",
    },
    "Differentiating": {
        "score_range": (3.50, 5.00),
        "accent":     "185F60",
        "card_bg":    "E8F7F6",
        "label_text": "185F60",
    },
}

LEVEL_5TIER = {
    1: {
        "score_range": (0.00, 0.99),
        "label":      "Foundational",
        "bg_rect":    "FFCB99",
        "circle":     "FE9732",
        "num_text":   "F2F4F9",
        "label_text": "1C4A4D",
    },
    2: {
        "score_range": (1.00, 1.99),
        "label":      "Developing",
        "bg_rect":    "C7D3EC",
        "circle":     "8094C0",
        "num_text":   "F2F4F9",
        "label_text": "1C4A4D",
    },
    3: {
        "score_range": (2.00, 2.99),
        "label":      "Established",
        "bg_rect":    "E6F3FA",
        "circle":     "3D81F6",
        "num_text":   "F2F4F9",
        "label_text": "1C4A4D",
    },
    4: {
        "score_range": (3.00, 3.99),
        "label":      "Advanced",
        "bg_rect":    "E8F7F6",
        "circle":     "62D7B8",
        "num_text":   "F2F4F9",
        "label_text": "1C4A4D",
    },
    5: {
        "score_range": (4.00, 5.00),
        "label":      "Transformational",
        "bg_rect":    "B0EED3",  # brand standard; theme has B0EDD3 — explicit srgbClr wins
        "circle":     "27BBAF",
        "num_text":   "FFFFFF",
        "label_text": "1C4A4D",
    },
}


# ══════════════════════════════════════════════════════════════════════════════
# 2. STATIC COLORS
# ══════════════════════════════════════════════════════════════════════════════
# Fixed across all decks. QA verifies these were preserved on every edited slide.
# Keys are referenced by per-slide role catalogues below.

STATIC_COLORS = {
    # Heatmap infrastructure
    "track_bar":        "E5E7EB",  # Slide 14 offset +4 fill+border — fixed
    "median_stroke":    "3D81F6",  # Slide 14 offset +6 cxnSp line stroke
    # Zennify brand accents
    "zennify_teal":         "27BBAF",  # priority strips, metric accents
    "zennify_mint_bg":      "E8F7F6",  # metric card bgs, strengths bg
    "zennify_light_purple": "F2F4F9",  # top banners, icon chips, Building card bg (also level-4tier Building card_bg)
    "zennify_dark_teal":    "1C4A4D",  # body text, score text, capability names
    "zennify_muted_header": "8094C0",  # eyebrows, footers (also = 4-tier Building accent)
    "zennify_muted_body":   "3D5A5C",  # priority descriptions, platforms, metric context
    # Slide 10 legend strip (Peer benchmarks)
    "s10_legend_act_bg":    "FFF3E8",
    "s10_legend_act_acc":   "F97316",
    "s10_legend_bld_bg":    "F2F4F9",
    "s10_legend_bld_acc":   "8094C0",
    "s10_legend_cmp_bg":    "E6F5F3",
    "s10_legend_cmp_acc":   "27BBAF",
    # Slide 10 competitive strengths panel
    "s10_strengths_bg":     "E8F7F6",
    "s10_strengths_accent": "139F94",  # legacy teal — distinct from 27BBAF; preserved
    # Slide 6 logo frame
    "s6_logo_frame":        "E0EEF0",
    # Slide 14 level legend (matches 4-tier palette)
    "s14_legend_act_bg":    "FFF3E8",
    "s14_legend_act_acc":   "F97316",
    "s14_legend_bld_bg":    "F2F4F9",
    "s14_legend_bld_acc":   "8094C0",
    "s14_legend_cmp_bg":    "E6F5F3",
    "s14_legend_cmp_acc":   "27BBAF",
    "s14_legend_dif_acc":   "185F60",  # Differentiating legend uses border-only (Sh11/Sh12)
}


# ══════════════════════════════════════════════════════════════════════════════
# 3. THEME REFERENCES (per Decision 4 — "use whatever is on the slides")
# ══════════════════════════════════════════════════════════════════════════════
# These shapes intentionally carry schemeClr references rather than explicit
# srgbClr, so they adapt if the theme changes. Editors MUST leave these alone;
# QA verifies the schemeClr element is still present with the expected `val`.

THEME_REFS = {
    # Slide 13 decorative bars (tops/bottoms)
    "s13_bar_top_1": "lt2",
    "s13_bar_top_2": "lt2",
    "s13_bar_top_3": "lt2",
    "s13_bar_top_4": "lt2",
    # Slide 13 pillar-row background tints
    "s13_pillar_row_bg_1": "lt2",
    "s13_pillar_row_bg_2": "lt2",
    "s13_pillar_row_bg_3": "lt2",
    "s13_pillar_row_bg_4": "lt2",
    # Slide 6 logo placeholder
    "s6_logo_placeholder_fill": "lt1",
    # Slide 16 opportunity card bgs + arrow
    "s16_opportunity_bg_1": "lt2",
    "s16_opportunity_bg_2": "lt2",
    "s16_opportunity_bg_3": "lt2",
    "s16_left_panel_bg":    "lt2",
    "s16_arrow_fill":       "accent4",
    "s16_arrow_border":     "dk2",
}


# ══════════════════════════════════════════════════════════════════════════════
# 4. SCORE-TO-LEVEL MAPPING
# ══════════════════════════════════════════════════════════════════════════════

def score_to_level_4tier(score: float) -> str:
    """Map a 0.0–5.0 score to the 4-tier heatmap/dashboard level."""
    if not (0.0 <= score <= 5.0):
        raise ValueError(f"score {score} out of range 0.0–5.0")
    if score < 1.50:
        return "Activating"
    elif score < 2.50:
        return "Building"
    elif score < 3.50:
        return "Competing"
    else:
        return "Differentiating"


def score_to_level_5tier(score: float) -> int:
    """Map a 0.0–5.0 score to the 5-tier Slide 13 maturity level (1–5)."""
    if not (0.0 <= score <= 5.0):
        raise ValueError(f"score {score} out of range 0.0–5.0")
    if score < 1.00:
        return 1
    elif score < 2.00:
        return 2
    elif score < 3.00:
        return 3
    elif score < 4.00:
        return 4
    else:
        return 5


# ══════════════════════════════════════════════════════════════════════════════
# 5. CONTENT-TYPE CONSTANTS (for readability in role catalogues)
# ══════════════════════════════════════════════════════════════════════════════
# Each role tuple uses the schema:
#   (role_name, content_type, source, palette_key, wf, wb, wt, wtc)
# Where:
#   content_type ∈ {"data", "static", "theme_ref", "text", "image"}
#   source:       for "data"  → dot-path to input like "s10.rec_scores[2]"
#                 for "static" → STATIC_COLORS key
#                 for "theme_ref" → THEME_REFS key
#                 for "text"  → description of text source
#                 for "image" → description of image source
#   palette_key:  for "data"  → key into LEVEL_4TIER or LEVEL_5TIER
#                 (ignored for non-data types)
#   wf, wb, wt, wtc: write-fill / write-border / write-text / write-text-color flags

# Boolean literals used in role tuples (readability)
T, F = True, False


# ══════════════════════════════════════════════════════════════════════════════
# 6. PER-SLIDE ROLE CATALOGUES
# ══════════════════════════════════════════════════════════════════════════════
# Each dict maps python-pptx shape index → role tuple.
# Shapes NOT present in the dict are "do not touch" — editors skip them; QA may
# optionally spot-check them for regression but does not expect specific content.

# ─── Slide 1 (Cover, 3 shapes) ────────────────────────────────────────────────
SLIDE_1_ROLES = {
    0: ("title_headline",  "text",  "input.headline",          None, F, F, T, F),
    1: ("tagline",         "text",  "sv.tagline + ' ' + date", None, F, F, T, F),
    2: ("client_logo",     "image", "input.client_logo",       None, F, F, F, F),
}

# ─── Slide 3 (Company Overview, 37 shapes — only Sh3 is edited) ──────────────
SLIDE_3_ROLES = {
    3: ("sv_descriptor", "text", "sv.descriptor", None, F, F, T, F),
}

# ─── Slide 6 (Org Profile, 40 shapes) ─────────────────────────────────────────
SLIDE_6_ROLES = {
    # Static structural colors — must be preserved
    0:  ("top_banner",       "static", "zennify_light_purple", None, F, F, F, F),
    3:  ("logo_frame",       "static", "s6_logo_frame",        None, F, F, F, F),
    4:  ("logo_placeholder", "theme_ref", "s6_logo_placeholder_fill", None, F, F, F, F),
    10: ("p1_strip",         "static", "zennify_teal",         None, F, F, F, F),
    13: ("p2_strip",         "static", "zennify_teal",         None, F, F, F, F),
    16: ("p3_strip",         "static", "zennify_teal",         None, F, F, F, F),
    26: ("m1_card_bg",       "static", "zennify_mint_bg",      None, F, F, F, F),
    30: ("m2_card_bg",       "static", "zennify_mint_bg",      None, F, F, F, F),
    34: ("m3_card_bg",       "static", "zennify_mint_bg",      None, F, F, F, F),
    # Text replacements
    1:  ("eyebrow",         "text", "'WHAT WE KNOW ABOUT ' + client.upper()", None, F, F, T, F),
    2:  ("headline",        "text", "input.headline",                        None, F, F, T, F),
    5:  ("fact_founded",    "text", "'Founded: ' + year + ', ' + state",     None, F, F, T, F),
    6:  ("fact_assets",     "text", "'Assets: $' + amount",                  None, F, F, T, F),
    7:  ("fact_branches",   "text", "'Branches: ' + n + '+ in ' + n + ' states'", None, F, F, T, F),
    8:  ("fact_employees",  "text", "'Employees: ~' + count",                None, F, F, T, F),
    11: ("p1_name",         "text", "input.priorities[0].name",              None, F, F, T, F),
    12: ("p1_desc",         "text", "input.priorities[0].desc",              None, F, F, T, F),
    14: ("p2_name",         "text", "input.priorities[1].name",              None, F, F, T, F),
    15: ("p2_desc",         "text", "input.priorities[1].desc",              None, F, F, T, F),
    17: ("p3_name",         "text", "input.priorities[2].name",              None, F, F, T, F),
    18: ("p3_desc",         "text", "input.priorities[2].desc",              None, F, F, T, F),
    20: ("platform_1",      "text", "input.platforms[0]",                    None, F, F, T, F),
    21: ("platform_2",      "text", "input.platforms[1]",                    None, F, F, T, F),
    22: ("platform_3",      "text", "input.platforms[2]",                    None, F, F, T, F),
    23: ("platform_4",      "text", "input.platforms[3]",                    None, F, F, T, F),
    24: ("platform_5",      "text", "input.platforms[4]",                    None, F, F, T, F),
    25: ("platform_summary","text", "input.platform_summary",                None, F, F, T, F),
    27: ("m1_label",        "text", "input.metrics[0].label",                None, F, F, T, F),
    28: ("m1_value",        "text", "input.metrics[0].value",                None, F, F, T, F),
    29: ("m1_context",      "text", "input.metrics[0].context",              None, F, F, T, F),
    31: ("m2_label",        "text", "input.metrics[1].label",                None, F, F, T, F),
    32: ("m2_value",        "text", "input.metrics[1].value",                None, F, F, T, F),
    33: ("m2_context",      "text", "input.metrics[1].context",              None, F, F, T, F),
    35: ("m3_label",        "text", "input.metrics[2].label",                None, F, F, T, F),
    36: ("m3_value",        "text", "input.metrics[2].value",                None, F, F, T, F),
    37: ("m3_context",      "text", "input.metrics[2].context",              None, F, F, T, F),
    # DO NOT TOUCH: Sh9/19 (section headers), Sh38 (icon image), Sh39 (footer)
}

# ─── Slide 9 (What is a DMA? — STATIC in this template) ──────────────────────
# Per finding F6: Slide 9 is a static explainer, NOT a per-deck DMA summary.
# The per-deck DMA summary is Slide 10. SLIDE_9_ROLES is deliberately empty.
SLIDE_9_ROLES = {}

# ─── Slide 10 (DMA Summary Dashboard, 44 shapes) ──────────────────────────────
SLIDE_10_ROLES = {
    # Data-driven pillar accent strips (4-tier) — writes FILL ONLY (template noFill borders)
    16: ("p1_pillar_strip", "data", "s10.pillar_scores.P1", "accent", T, F, F, F),
    15: ("p2_pillar_strip", "data", "s10.pillar_scores.P2", "accent", T, F, F, F),
    14: ("p3_pillar_strip", "data", "s10.pillar_scores.P3", "accent", T, F, F, F),
    2:  ("p4_pillar_strip", "data", "s10.pillar_scores.P4", "accent", T, F, F, F),
    # Data-driven rec cards — writes FILL AND BORDER (fix for missed border edits)
    17: ("rec1_card_bg",    "data", "s10.rec_scores[0]", "card_bg",    T, T, F, F),
    18: ("rec1_strip",      "data", "s10.rec_scores[0]", "accent",     T, T, F, F),
    19: ("rec1_label",      "data", "s10.rec_scores[0]", "label_text", F, F, T, T),
    20: ("rec2_card_bg",    "data", "s10.rec_scores[1]", "card_bg",    T, T, F, F),
    21: ("rec2_strip",      "data", "s10.rec_scores[1]", "accent",     T, T, F, F),
    22: ("rec2_label",      "data", "s10.rec_scores[1]", "label_text", F, F, T, T),
    23: ("rec3_card_bg",    "data", "s10.rec_scores[2]", "card_bg",    T, T, F, F),
    24: ("rec3_strip",      "data", "s10.rec_scores[2]", "accent",     T, T, F, F),
    25: ("rec3_label",      "data", "s10.rec_scores[2]", "label_text", F, F, T, T),
    # Static — peer benchmarks legend strip (Sh26-34)
    26: ("legend_act_bg",   "static", "s10_legend_act_bg",  None, F, F, F, F),
    27: ("legend_act_acc",  "static", "s10_legend_act_acc", None, F, F, F, F),
    29: ("legend_bld_bg",   "static", "s10_legend_bld_bg",  None, F, F, F, F),
    30: ("legend_bld_acc",  "static", "s10_legend_bld_acc", None, F, F, F, F),
    32: ("legend_cmp_bg",   "static", "s10_legend_cmp_bg",  None, F, F, F, F),
    33: ("legend_cmp_acc",  "static", "s10_legend_cmp_acc", None, F, F, F, F),
    # Static — competitive strengths panel
    40: ("strengths_bg",     "static", "s10_strengths_bg",     None, F, F, F, F),
    41: ("strengths_accent", "static", "s10_strengths_accent", None, F, F, F, F),
    # Text replacements (colors inherited from template, not written)
    1:  ("headline",   "text", "'Where ' + client + ' stands and what comes next'",         None, F, F, T, F),
    7:  ("narrative",  "text", "Sh7 rewrite: replace [Client], overall, peer + sentence 2-3", None, F, F, T, F),
    9:  ("p2_name",    "text", "sv.p2_name_override OR 'Customer Experience'",              None, F, F, T, F),
    12: ("p1_insight", "text", "input.pillars.P1.insight",                                  None, F, F, T, F),
    8:  ("p2_insight", "text", "input.pillars.P2.insight",                                  None, F, F, T, F),
    10: ("p3_insight", "text", "input.pillars.P3.insight",                                  None, F, F, T, F),
    3:  ("p4_insight", "text", "input.pillars.P4.insight",                                  None, F, F, T, F),
    36: ("rec1_name",  "text", "recs[0].name + ' | Maturity: ' + cur + ' → Target: ' + tgt", None, F, F, T, F),
    37: ("rec2_name",  "text", "recs[1].name + ' | Maturity: ' + cur + ' → Target: ' + tgt", None, F, F, T, F),
    38: ("rec3_name",  "text", "recs[2].name + ' | Maturity: ' + cur + ' → Target: ' + tgt", None, F, F, T, F),
    42: ("strengths",  "text", "input.strengths[0] + '\\n' + input.strengths[1]",           None, F, F, T, F),
    # DO NOT TOUCH: Sh0/5/6/35/39/43 (eyebrow, off-canvas title, section headers, closing tagline)
    # DO NOT TOUCH: Sh11/13/28/31/34 (pillar name labels — static except Sh9 via P2 override)
    # DO NOT TOUCH: Sh4 (P4 pillar name — "Data & Tech", static)
}

# ─── Slide 13 (Key Strengths + Assessment, 46 shapes) ─────────────────────────
SLIDE_13_ROLES = {
    # Theme-ref backgrounds — editors leave alone; QA verifies schemeClr preserved
    0:  ("bar_top_1",         "theme_ref", "s13_bar_top_1", None, F, F, F, F),
    1:  ("bar_top_2",         "theme_ref", "s13_bar_top_2", None, F, F, F, F),
    2:  ("bar_top_3",         "theme_ref", "s13_bar_top_3", None, F, F, F, F),
    3:  ("bar_top_4",         "theme_ref", "s13_bar_top_4", None, F, F, F, F),
    15: ("pillar_row_bg_1",   "theme_ref", "s13_pillar_row_bg_1", None, F, F, F, F),
    16: ("pillar_row_bg_2",   "theme_ref", "s13_pillar_row_bg_2", None, F, F, F, F),
    17: ("pillar_row_bg_3",   "theme_ref", "s13_pillar_row_bg_3", None, F, F, F, F),
    18: ("pillar_row_bg_4",   "theme_ref", "s13_pillar_row_bg_4", None, F, F, F, F),
    # Data-driven 5-tier pillar level indicators
    19: ("p1_bg_rect", "data", "s13.pillar_levels.P1", "bg_rect",    T, F, F, F),
    20: ("p1_circle",  "data", "s13.pillar_levels.P1", "circle",     T, F, F, F),
    21: ("p1_number",  "data", "s13.pillar_levels.P1", "num_text",   F, F, T, T),
    22: ("p1_label",   "data", "s13.pillar_levels.P1", "label_text", F, F, T, T),
    23: ("p2_bg_rect", "data", "s13.pillar_levels.P2", "bg_rect",    T, F, F, F),
    24: ("p2_circle",  "data", "s13.pillar_levels.P2", "circle",     T, F, F, F),
    25: ("p2_number",  "data", "s13.pillar_levels.P2", "num_text",   F, F, T, T),
    26: ("p2_label",   "data", "s13.pillar_levels.P2", "label_text", F, F, T, T),
    27: ("p3_bg_rect", "data", "s13.pillar_levels.P3", "bg_rect",    T, F, F, F),
    28: ("p3_circle",  "data", "s13.pillar_levels.P3", "circle",     T, F, F, F),
    29: ("p3_number",  "data", "s13.pillar_levels.P3", "num_text",   F, F, T, T),
    30: ("p3_label",   "data", "s13.pillar_levels.P3", "label_text", F, F, T, T),
    31: ("p4_bg_rect", "data", "s13.pillar_levels.P4", "bg_rect",    T, F, F, F),
    32: ("p4_circle",  "data", "s13.pillar_levels.P4", "circle",     T, F, F, F),
    33: ("p4_number",  "data", "s13.pillar_levels.P4", "num_text",   F, F, T, T),
    34: ("p4_label",   "data", "s13.pillar_levels.P4", "label_text", F, F, T, T),
    # Text replacements
    6:  ("strength_1",        "text", "input.strengths[0]",                   None, F, F, T, F),
    7:  ("strength_2",        "text", "input.strengths[1]",                   None, F, F, T, F),
    9:  ("strength_3",        "text", "input.strengths[2]",                   None, F, F, T, F),
    10: ("strength_4",        "text", "input.strengths[3]",                   None, F, F, T, F),
    11: ("narrative_headline","text", "input.headline",                       None, F, F, T, F),
    12: ("assessment_title",  "text", "client + ' Assessment'",               None, F, F, T, F),
    13: ("comparison_title",  "text", "client + ' Overall Maturity Industry Comparison'", None, F, F, T, F),
    # Image replacements
    44: ("radar_chart",       "image", "radar_chart_generator.py",            None, F, F, F, F),
    45: ("radar_legend",      "image", "radar_chart_generator.py",            None, F, F, F, F),
    # DO NOT TOUCH: Sh5 'Key Strengths' header, Sh14 'THE ASSESSMENT', Sh35-43 tick-mark pictures, Sh8 empty
}

# ─── Slide 14 (Heatmap, 158 shapes — 17 capability blocks × 8 offsets + 17 shared) ──
# The 17 block bases:
BLOCKS_158 = [17, 25, 33, 41, 49, 58, 66, 74, 82, 91, 99, 107, 115, 124, 132, 140, 148]

# Canonical capability order (must match DMA input data)
CAPABILITY_ORDER = [
    "Digital Strategy & Vision",      # P1
    "Governance & Risk Appetite",     # P1
    "Innovation Management",          # P1
    "Culture & Change Enablement",    # P1
    "Sustainable Finance & ESG",      # P1
    "Digital Marketing & Acquisition",# P2
    "Onboarding & Fulfillment",       # P2
    "Omnichannel Servicing",          # P2
    "Personalization & Engagement",   # P2
    "Process Automation",             # P3
    "Operational Risk & Fraud",       # P3
    "Compliance & Surveillance",      # P3
    "Business Resilience & TPRM",     # P3
    "Data Governance",                # P4
    "Analytics & AI Enablement",      # P4
    "Architecture & Integration",     # P4
    "Platform Enablement",            # P4
]

# Per-block-offset roles (shared by all 17 blocks — used in a loop)
SLIDE_14_BLOCK_OFFSETS = {
    0: ("bg_card",      "data",   "cap.score",           "card_bg",    T, T, F, F),
    1: ("accent_strip", "data",   "cap.score",           "accent",     T, T, F, F),
    2: ("cap_name",     "text",   "cap.name + terminology", None,        F, F, T, F),
    3: ("score",        "text",   "cap.score formatted as X.X", None,    F, F, T, F),
    4: ("track_bar",    "static", "track_bar",           None,         T, T, F, F),
    5: ("progress_bar", "data",   "cap.score",           "accent",     T, T, F, F),  # ALSO width
    6: ("median_line",  "static", "median_stroke",       None,         F, F, F, F),  # cxnSp — x position via special logic
    7: ("level_label",  "data",   "cap.score",           "label_text", F, F, T, T),
}

# Non-block shapes on Slide 14 (headline, pillar headers, legend, median-legend line)
SLIDE_14_SHARED_ROLES = {
    # Headline
    1:  ("headline", "text", "input.headline", None, F, F, T, F),
    # Level legend strip (rendered in the 4-tier order: Activating / Building / Competing / Differentiating)
    2:  ("legend_act_bg",          "static", "s14_legend_act_bg",  None, T, T, F, F),
    3:  ("legend_act_acc",         "static", "s14_legend_act_acc", None, T, T, F, F),
    5:  ("legend_bld_bg",          "static", "s14_legend_bld_bg",  None, T, T, F, F),
    6:  ("legend_bld_acc",         "static", "s14_legend_bld_acc", None, T, T, F, F),
    8:  ("legend_cmp_bg",          "static", "s14_legend_cmp_bg",  None, T, T, F, F),
    9:  ("legend_cmp_acc",         "static", "s14_legend_cmp_acc", None, T, T, F, F),
    12: ("legend_dif_acc",         "static", "s14_legend_dif_acc", None, T, T, F, F),
    # Median legend line (connector, stroke only)
    14: ("median_legend_line",     "static", "median_stroke",      None, F, F, F, F),
    # DO NOT TOUCH: Sh0/9 (eyebrows), Sh4/7/10/13/15 (legend text labels),
    # Sh11 (differentiating color chip border only), Sh16 + pillar headers at
    # column positions (static text)
}

# ─── Slide 16 (Opportunities, 14 shapes) ──────────────────────────────────────
SLIDE_16_ROLES = {
    # Theme-ref backgrounds (adapt with theme)
    0:  ("left_panel_bg",     "theme_ref", "s16_left_panel_bg",   None, F, F, F, F),
    5:  ("opp_card_1_bg",     "theme_ref", "s16_opportunity_bg_1",None, F, F, F, F),
    6:  ("opp_card_2_bg",     "theme_ref", "s16_opportunity_bg_2",None, F, F, F, F),
    7:  ("opp_card_3_bg",     "theme_ref", "s16_opportunity_bg_3",None, F, F, F, F),
    # Arrow — theme ref for both fill (accent4) and border (dk2) per template
    11: ("arrow",             "theme_ref", "s16_arrow_fill",      None, F, F, F, F),
    # Text replacements — opportunity cards have BOLD header line + regular body
    3:  ("headline",   "text", "input.headline",                                   None, F, F, T, F),
    4:  ("intro",      "text", "input.opportunity_intro",                          None, F, F, T, F),
    8:  ("opp_card_1", "text", "opportunities[0]: bold name + Maturity Gap + Why", None, F, F, T, F),
    9:  ("opp_card_2", "text", "opportunities[1]: same structure",                 None, F, F, T, F),
    10: ("opp_card_3", "text", "opportunities[2]: same structure",                 None, F, F, T, F),
    12: ("outcomes",   "text", "input.outcomes (3-5 bullets)",                     None, F, F, T, F),
    # DO NOT TOUCH: Sh2 'OPPORTUNITIES' eyebrow, Sh13 'OUTCOMES' header
}

# ─── Slide 20 (Mobilization Close, 21 shapes) ────────────────────────────────
SLIDE_20_ROLES = {
    # Static F2F4F9 icon-chip backgrounds — 8 chips (bullet markers)
    4:  ("step_chip_1",   "static", "zennify_light_purple", None, F, F, F, F),
    6:  ("step_chip_2",   "static", "zennify_light_purple", None, F, F, F, F),
    8:  ("step_chip_3",   "static", "zennify_light_purple", None, F, F, F, F),
    10: ("step_chip_4",   "static", "zennify_light_purple", None, F, F, F, F),
    13: ("deliv_chip_1",  "static", "zennify_light_purple", None, F, F, F, F),
    15: ("deliv_chip_2",  "static", "zennify_light_purple", None, F, F, F, F),
    17: ("deliv_chip_3",  "static", "zennify_light_purple", None, F, F, F, F),
    19: ("deliv_chip_4",  "static", "zennify_light_purple", None, F, F, F, F),
    # Text replacements
    0:  ("next_steps_body",   "text", "input.next_steps (≥3 rows: Date|Action|Owner)", None, F, F, T, F),
    2:  ("goal_statement",    "text", "input.goal_statement",                          None, F, F, T, F),
    3:  ("headline",          "text", "input.headline",                                None, F, F, T, F),
    12: ("deliverables_body", "text", "input.deliverables (≥3 items)",                 None, F, F, T, F),
    # DO NOT TOUCH: Sh1 (slide number), Sh5/7/9/11/14/16/18/20 (PlaceholderPicture icons)
}

# ─── Slide 21 (Contact, 2 shapes) ────────────────────────────────────────────
SLIDE_21_ROLES = {
    0: ("presenter_email", "text", "input.presenter_email", None, F, F, T, F),
    # DO NOT TOUCH: Sh1 "Let's move forward together."
}

# ══════════════════════════════════════════════════════════════════════════════
# 7. ROLE-CATALOGUE AGGREGATOR
# ══════════════════════════════════════════════════════════════════════════════

ALL_SLIDE_ROLES = {
    1:  SLIDE_1_ROLES,
    3:  SLIDE_3_ROLES,
    6:  SLIDE_6_ROLES,
    9:  SLIDE_9_ROLES,
    10: SLIDE_10_ROLES,
    13: SLIDE_13_ROLES,
    14: {**SLIDE_14_SHARED_ROLES},  # block roles expanded at runtime
    16: SLIDE_16_ROLES,
    20: SLIDE_20_ROLES,
    21: SLIDE_21_ROLES,
}


def expand_slide14_blocks():
    """Expand SLIDE_14_BLOCK_OFFSETS × BLOCKS_158 into a full shape-index dict.

    Returns a dict mapping python-pptx shape_idx → role tuple for all 136
    block shapes (17 blocks × 8 offsets). The caller merges this with
    SLIDE_14_SHARED_ROLES to get the complete Slide 14 role catalogue.
    """
    block_roles = {}
    for block_num, base in enumerate(BLOCKS_158):
        cap_name = CAPABILITY_ORDER[block_num]
        for offset, (role_name, ctype, source, palette_key, wf, wb, wt, wtc) in SLIDE_14_BLOCK_OFFSETS.items():
            shape_idx = base + offset
            # Specialize role name per capability (e.g., "bg_card_cap01")
            specialized_role = f"{role_name}_cap{block_num+1:02d}"
            # Specialize source to point at the specific capability
            if ctype == "data":
                specialized_source = f"s14.scores[{block_num}]"  # cap index
            elif ctype == "text" and "cap.score" in source:
                specialized_source = f"s14.scores[{block_num}] formatted"
            elif ctype == "text" and "cap.name" in source:
                specialized_source = f"CAPABILITY_ORDER[{block_num}] = {cap_name!r}"
            else:
                specialized_source = source
            block_roles[shape_idx] = (specialized_role, ctype, specialized_source, palette_key, wf, wb, wt, wtc)
    return block_roles


def get_slide14_full_roles():
    """Return Slide 14 complete role catalogue: shared + expanded per-block."""
    return {**SLIDE_14_SHARED_ROLES, **expand_slide14_blocks()}


# ══════════════════════════════════════════════════════════════════════════════
# 8. EXPECTED-HEX RESOLVER (used by both editors and QA)
# ══════════════════════════════════════════════════════════════════════════════

def resolve_data_source(source_path: str, input_data: dict):
    """Walk a dotted path like 's10.rec_scores[2]' against input_data."""
    import re
    # Strip leading namespace ('s10.', 's13.', 's14.', 'input.', 'cap.', 'sv.')
    # For now, support the literal paths used in role catalogues
    parts = re.split(r'\.|\[|\]', source_path)
    parts = [p for p in parts if p]  # drop empties from split

    cur = input_data
    for p in parts:
        if p.isdigit():
            cur = cur[int(p)]
        else:
            if isinstance(cur, dict):
                if p in cur:
                    cur = cur[p]
                else:
                    raise KeyError(f"Key {p!r} not found in input (path: {source_path!r})")
            else:
                # Attribute-style access — we don't support this yet; paths use dict access
                raise TypeError(f"Cannot descend into {type(cur).__name__} with key {p!r}")
    return cur


def get_expected_hex(role_spec, input_data, slide_num=None):
    """Given a role tuple, input data, and (for data roles) the slide number,
    return the expected hex string.

    Returns None for text/image roles (no color to verify).
    For "data" roles: derives hex via score_to_level_* → LEVEL_*TIER[level][palette_key]
    For "static" roles: looks up STATIC_COLORS[source]
    For "theme_ref" roles: returns "scheme:" + the schemeClr val (caller checks XML)

    slide_num discriminates 4-tier vs 5-tier palettes since `label_text` is a key
    in both. Slide 13 → 5-tier; Slides 10, 14 → 4-tier.
    """
    role_name, ctype, source, palette_key, wf, wb, wt, wtc = role_spec

    if ctype == "text" or ctype == "image":
        return None

    if ctype == "static":
        if source not in STATIC_COLORS:
            raise KeyError(f"STATIC_COLORS has no key {source!r} (role {role_name})")
        return STATIC_COLORS[source]

    if ctype == "theme_ref":
        if source not in THEME_REFS:
            raise KeyError(f"THEME_REFS has no key {source!r} (role {role_name})")
        val = THEME_REFS[source]
        return f"scheme:{val}" if val is not None else None

    if ctype == "data":
        if input_data is None:
            return None  # caller doesn't have the inputs; can't resolve
        if slide_num is None:
            raise ValueError(
                f"get_expected_hex requires slide_num for data role {role_name!r} "
                f"to disambiguate 4-tier vs 5-tier palette"
            )
        score = resolve_data_source(source, input_data)
        if slide_num == 13:
            level = score_to_level_5tier(score)
            if palette_key not in LEVEL_5TIER[level]:
                raise KeyError(f"LEVEL_5TIER[{level!r}] has no key {palette_key!r}")
            return LEVEL_5TIER[level][palette_key]
        elif slide_num in (10, 14):
            level = score_to_level_4tier(score)
            if palette_key not in LEVEL_4TIER[level]:
                raise KeyError(f"LEVEL_4TIER[{level!r}] has no key {palette_key!r}")
            return LEVEL_4TIER[level][palette_key]
        else:
            raise ValueError(
                f"No palette assigned for data role on slide {slide_num!r} "
                f"(role {role_name!r})"
            )

    raise ValueError(f"Unknown content_type {ctype!r} in role {role_name!r}")


# ══════════════════════════════════════════════════════════════════════════════
# 9. PUBLIC API SUMMARY (what editors and QA should import)
# ══════════════════════════════════════════════════════════════════════════════

__all__ = [
    # Palettes
    "LEVEL_4TIER", "LEVEL_5TIER",
    # Static + theme refs
    "STATIC_COLORS", "THEME_REFS",
    # Score→level
    "score_to_level_4tier", "score_to_level_5tier",
    # Role catalogues
    "SLIDE_1_ROLES", "SLIDE_3_ROLES", "SLIDE_6_ROLES", "SLIDE_9_ROLES",
    "SLIDE_10_ROLES", "SLIDE_13_ROLES", "SLIDE_16_ROLES", "SLIDE_20_ROLES",
    "SLIDE_21_ROLES", "SLIDE_14_SHARED_ROLES", "SLIDE_14_BLOCK_OFFSETS",
    "BLOCKS_158", "CAPABILITY_ORDER",
    "ALL_SLIDE_ROLES",
    # Helpers
    "expand_slide14_blocks", "get_slide14_full_roles",
    "get_expected_hex", "resolve_data_source",
    # Truth-value helpers for readability
    "T", "F",
]
