#!/usr/bin/env python3
"""Generate the customer-audience serve allowlist from the contract.

The serve boundary was deny-based for its whole life: four ordered strip
mechanisms, each added after a measured leak (r_layer on 36 paths, personal
LinkedIn URLs on four unmarked roster rows, the evidence census on the wire
behind a UI accident). Deny-based means the NEXT internal-shaped key — the
one nobody thought to deny — serves by default. This flips the default for
the customer audience: what serves is what this file emits, and a key the
contract gains tomorrow is ABSENT from the allowlist until somebody
classifies it here.

Derivation, not authorship: allowed = the contract's own field and item-key
vocabulary (apps/mcp/dma_mcp/contracts_data.json via the same readers the
gates use) MINUS the excluded key classes in packages/shared/serve_classes.json
(probe ladders, evidence-method vocabulary, cap vocabulary). Envelope keys
are allowed globally except where a class excludes a subkey.

Output: apps/api/dma_api/customer_allowlist.json — committed, and pinned by
apps/api/tests/test_customer_allowlist.py which regenerates and diffs, so a
contract change that widens the serve surface fails CI until classified.

Run from the repo root:  python scripts/gen_customer_allowlist.py
"""
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "apps" / "mcp"))
sys.path.insert(0, str(ROOT / "packages" / "shared"))

from dma_mcp.contracts import PAGES, sections  # noqa: E402
from dma_mcp.vacuity import item_keys  # noqa: E402

CLASSES = json.loads(
    (ROOT / "packages" / "shared" / "serve_classes.json").read_text())
EXCLUDED = frozenset(
    k for cls in ("probe_keys", "method_keys", "cap_keys")
    for k in CLASSES[cls]["keys"])

# empty_state serves the reader its reason and its closure condition — the
# 2026-08-14 adjudication — never its search rungs (probe class).
EMPTY_STATE_KEYS = ("reason", "closure_condition", "closure", "kind")


def build() -> dict:
    contracts = (ROOT / "apps" / "mcp" / "dma_mcp" / "contracts_data.json")
    # The contract's item grammar is narrower than the promoted reality
    # (platform_story's "Per item:" describes the gaps row, not the card),
    # so allowed keys are the UNION of the contract and the observed
    # reference surface — Baxter, the positive pattern, and Logix — per the
    # program rule that the allowlist derives from the reference client-
    # facing surface set. New keys remain default-deny: they are in neither.
    reference = json.loads(
        (ROOT / "fixtures" / "reference_surface_keys.json").read_text())
    out = {
        "_doc": "Customer-audience serve allowlist. GENERATED by "
                "scripts/gen_customer_allowlist.py from the contract minus "
                "packages/shared/serve_classes.json — edit those, never this.",
        "generated_from_sha256": hashlib.sha256(
            contracts.read_bytes()).hexdigest(),
        "excluded_key_classes": sorted(EXCLUDED),
        "empty_state_keys": list(EMPTY_STATE_KEYS),
        "sections": {},
    }
    for page in PAGES:
        for name, spec in sections(page).items():
            ref = reference["sections"].get(f"{page}.{name}", {})
            allowed = sorted(
                (set(spec["fields"]) | set(ref.get("keys", ())))
                - EXCLUDED)
            items = {}
            fields = set(spec["fields"]) | set(ref.get("items", {}))
            for field in fields:
                ks = set(item_keys(page, name, field))
                ks |= set(ref.get("items", {}).get(field, ()))
                if ks:
                    items[field] = sorted(ks - EXCLUDED)
            out["sections"][f"{page}.{name}"] = {
                "keys": allowed, **({"items": items} if items else {})}
    return out


def main() -> int:
    target = ROOT / "apps" / "api" / "dma_api" / "customer_allowlist.json"
    data = build()
    target.write_text(json.dumps(data, indent=1, sort_keys=True) + "\n")
    n = len(data["sections"])
    itemed = sum(1 for s in data["sections"].values() if s.get("items"))
    print(f"customer_allowlist.json: {n} sections, {itemed} with item-grain "
          f"keys, {len(EXCLUDED)} excluded keys")
    return 0


if __name__ == "__main__":
    sys.exit(main())
