#!/usr/bin/env python3
"""Generate the prototype's band resolver FROM the sanctioned one.

    gen_proto_bands.py [--check]

WHY THIS EXISTS. Charter invariant 7: "Score→band→hex in exactly one
frontend module." AUD-0048 measured two, and the UNSANCTIONED one winning
50 call sites to 1 — `apps/web/lib/bands.js` was imported by a single status
page while `apps/web/proto/data.js`'s own `maturityHex` / `maturityClass` /
`maturityLabel` served every rendered surface. AUD-0049 measured what the
second copy then did differently: `maturityHex(null)` returned `#E5E7EB`, a
grey swatch for a score that does not exist, which reads to a client as a
measurement that was taken and came out low — invariants 6 and 9 both.

The prototype's modules are CLASSIC scripts compiled by babel into
`public/proto/js/`; they cannot `import`. So the two files cannot be one
file. They can be one AUTHORED file: `lib/bands.js` is written by hand,
`proto/bands.js` is generated from it, loaded first, and every call site
delegates to it. `--check` fails the build when they diverge, which is the
guarantee the invariant actually needs — one place a human edits, and no
way for the other to drift quietly.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "apps" / "web" / "lib" / "bands.js"
TARGET = ROOT / "apps" / "web" / "proto" / "bands.js"

#: The class token each band renders with in the prototype's CSS. Part of
#: the resolver, so it lives beside the hexes rather than in a second table.
CLASSES = {"Activating": "b-act", "Building": "b-bld",
           "Competing": "b-cmp", "Differentiating": "b-dif"}


def read_source() -> tuple[list, dict]:
    """(ordered band names, {band: {fill, text}}) parsed from lib/bands.js."""
    src = SOURCE.read_text()
    body = src[src.index("export const BANDS = {"):]
    body = body[body.index("{"):body.index("};") + 1]
    bands, order = {}, []
    for m in re.finditer(
            r'(\w+):\s*\{\s*fill:\s*"(#[0-9A-Fa-f]{6})",\s*text:\s*"(#[0-9A-Fa-f]{6})"',
            body):
        order.append(m.group(1))
        bands[m.group(1)] = {"fill": m.group(2), "text": m.group(3)}
    if len(order) != 4:
        raise SystemExit(
            f"lib/bands.js defines {len(order)} bands; the enum is four "
            f"(invariant 6) and this generator will not emit a fifth")
    if any(b not in CLASSES for b in order):
        raise SystemExit(f"band without a CSS class: {set(order) - set(CLASSES)}")
    return order, bands


def render() -> str:
    order, bands = read_source()
    rows = ",\n".join(
        f'    {b}: {{ fill: "{bands[b]["fill"]}", text: "{bands[b]["text"]}", '
        f'cls: "{CLASSES[b]}" }}' for b in order)
    thresholds = "\n".join(
        f"    if (s < {i + 2}) return \"{b}\";"
        for i, b in enumerate(order[:-1]))
    return f'''/* GENERATED by scripts/gen_proto_bands.py from apps/web/lib/bands.js.
   DO NOT EDIT. Edit lib/bands.js; CI runs --check.

   The ONE score->band->hex resolver, in the form a classic script can use.
   Invariant 7 says exactly one frontend module maps a score to a colour;
   the prototype's modules cannot `import`, so this file is generated from
   that module rather than written a second time. Every call site in
   proto/*.jsx delegates here.

   Invariants 6 and 9, both in `bandFor`: four branches, strict less-than,
   on the RAW score before display rounding — and a null score returns null,
   never a grey swatch. A colour for "no score" is a measurement the client
   never had. */
(function (root) {{
  var BANDS = {{
{rows}
  }};

  function bandFor(rawScore) {{
    if (rawScore === null || rawScore === undefined) return null;
    var s = Number(rawScore);
    if (!isFinite(s)) return null;
{thresholds}
    return "{order[-1]}";
  }}

  function hexFor(rawScore) {{
    var b = bandFor(rawScore);
    return b ? BANDS[b].fill : null;   /* null, NOT a grey swatch */
  }}

  function classFor(rawScore) {{
    var b = bandFor(rawScore);
    return b ? BANDS[b].cls : "muted"; /* "muted" renders a dashed outline,
                                          which is an absence, not a fill */
  }}

  root.DMA_BANDS = {{
    BANDS: BANDS, bandFor: bandFor, hexFor: hexFor, classFor: classFor,
    labelFor: bandFor,
  }};
}})(typeof window !== "undefined" ? window : globalThis);
'''


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args(argv)
    body = render()
    if a.check:
        have = TARGET.read_text() if TARGET.exists() else ""
        if have != body:
            print("gen_proto_bands: proto/bands.js is STALE or hand-edited — "
                  "run scripts/gen_proto_bands.py")
            return 1
        print("gen_proto_bands: proto/bands.js matches lib/bands.js")
        return 0
    TARGET.write_text(body)
    print(f"gen_proto_bands: wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
