#!/usr/bin/env python3
"""Generate the customer-audience serve allowlist from the contract.

The serve boundary was deny-based for its whole life: four ordered strip
mechanisms, each added after a measured leak (r_layer on 36 paths, personal
LinkedIn URLs on four unmarked roster rows, the evidence census on the wire
behind a UI accident). Deny-based means the NEXT internal-shaped key — the
one nobody thought to deny — serves by default. This flips the default for
the customer audience: what serves is what this file emits, and a key the
contract gains tomorrow is ABSENT from the allowlist until somebody
classifies it here.

Derivation, not authorship: allowed = the contract's own field and item-key
vocabulary (apps/mcp/dma_mcp/contracts_data.json via the same readers the
gates use) MINUS the excluded key classes in packages/shared/serve_classes.json
(probe ladders, evidence-method vocabulary, cap vocabulary). Envelope keys
are allowed globally except where a class excludes a subkey.

Output: apps/api/dma_api/customer_allowlist.json — committed, and pinned by
apps/api/tests/test_customer_allowlist.py which regenerates and diffs, so a
contract change that widens the serve surface fails CI until classified.

Run from the repo root:  python scripts/gen_customer_allowlist.py
"""
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "apps" / "mcp"))
sys.path.insert(0, str(ROOT / "packages" / "shared"))

from dma_mcp.contracts import PAGES, sections  # noqa: E402
from dma_mcp.vacuity import item_keys  # noqa: E402

CLASSES = json.loads(
    (ROOT / "packages" / "shared" / "serve_classes.json").read_text())
EXCLUDED = frozenset(
    k for cls in ("probe_keys", "method_keys", "cap_keys")
    for k in CLASSES[cls]["keys"])

# empty_state serves the reader its reason and its closure condition — the
# 2026-08-14 adjudication — never its search rungs (probe class).
EMPTY_STATE_KEYS = ("reason", "closure_condition", "closure", "kind")


def build() -> dict:
    contracts = (ROOT / "apps" / "mcp" / "dma_mcp" / "contracts_data.json")
    # The contract's item grammar is narrower than the promoted reality
    # (platform_story's "Per item:" describes the gaps row, not the card),
    # so allowed keys are the UNION of the contract and the observed
    # reference surface — Baxter, the positive pattern, and Logix — per the
    # program rule that the allowlist derives from the reference client-
    # facing surface set. New keys remain default-deny: they are in neither.
    reference = json.loads(
        (ROOT / "fixtures" / "reference_surface_keys.json").read_text())
    # AN EMPTY REFERENCE IS NOT A NARROW SURFACE — it is a missing input,
    # and the difference is the whole incident of 2026-08-20. The fixture is
    # regenerated from the promoted reference clients by
    # scripts/gen_reference_surface_keys.py, which writes an EMPTY result
    # when it cannot reach the database. Regenerating the allowlist on top
    # of that empty fixture silently produced a list 49 keys narrower than
    # the reviewed one, and stripped client content from every customer
    # page. Refuse instead: a generator that quietly narrows the serve
    # surface when its input vanishes is worse than one that stops.
    # Check the SECTIONS, not the top-level keys. The corrupt shape this
    # guard exists for is {"_doc": "...", "sections": {}} — a dict with one
    # non-underscore key, so a truthiness test on the payload keys is TRUE
    # and the guard never fires. Caught by an independent verifier on
    # 2026-08-20, hours after the guard was written, on the very fixture it
    # was written for.
    if not reference.get("sections"):
        raise SystemExit(
            "fixtures/reference_surface_keys.json carries no sections — "
            "refusing to narrow the customer serve surface from an empty "
            "reference. Recover it first: `git checkout ff79471 -- "
            "fixtures/reference_surface_keys.json` restores the reviewed "
            "34-section fixture (verified 2026-08-20 to regenerate the "
            "committed allowlist byte-for-byte). Only if that is unavailable, "
            "rebuild it with scripts/gen_reference_surface_keys.py against "
            "the promoted reference payload snapshots, which needs the "
            "database.")
    out = {
        "_doc": "Customer-audience serve allowlist. GENERATED by "
                "scripts/gen_customer_allowlist.py from the contract minus "
                "packages/shared/serve_classes.json — edit those, never this.",
        "generated_from_sha256": hashlib.sha256(
            contracts.read_bytes()).hexdigest(),
        "excluded_key_classes": sorted(EXCLUDED),
        "empty_state_keys": list(EMPTY_STATE_KEYS),
        "sections": {},
    }
    for page in PAGES:
        for name, spec in sections(page).items():
            ref = reference["sections"].get(f"{page}.{name}", {})
            allowed = sorted(
                (set(spec["fields"]) | set(ref.get("keys", ())))
                - EXCLUDED)
            items = {}
            fields = set(spec["fields"]) | set(ref.get("items", {}))
            for field in fields:
                ks = set(item_keys(page, name, field))
                ks |= set(ref.get("items", {}).get(field, ()))
                if ks:
                    items[field] = sorted(ks - EXCLUDED)
            out["sections"][f"{page}.{name}"] = {
                "keys": allowed, **({"items": items} if items else {})}
    return out


def main(argv=None) -> int:
    """Write the allowlist, or — with --out/--check — do not touch the repo.

    WHY THE FLAGS EXIST (measured 2026-08-20): the test that was supposed to
    prove the committed file matched a fresh generation RAN THIS SCRIPT with
    no arguments, overwriting the tracked file, and then compared the file to
    itself. It could never fail, and it silently rewrote the working tree —
    so an ordinary `git add -A` after any test run committed a regenerated
    allowlist. That is exactly how 49 keys were removed from the customer
    serve surface in one commit nobody wrote.
    """
    import argparse

    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default=None,
                    help="write here instead of the tracked file")
    ap.add_argument("--check", action="store_true",
                    help="write nothing; exit 1 if the tracked file is not a "
                         "superset of a fresh generation")
    args = ap.parse_args(argv)

    tracked = ROOT / "apps" / "api" / "dma_api" / "customer_allowlist.json"
    data = build()
    if args.check:
        import sys as _sys
        have = json.loads(tracked.read_text())
        missing = []
        for sec, spec in data["sections"].items():
            hs = have["sections"].get(sec)
            if hs is None:
                missing.append(sec)
                continue
            for k in spec.get("keys", []):
                if k not in hs.get("keys", []):
                    missing.append(f"{sec}.{k}")
            for field, keys in (spec.get("items") or {}).items():
                for k in keys:
                    if k not in (hs.get("items") or {}).get(field, []):
                        missing.append(f"{sec}.{field}.{k}")
        if missing:
            print("the contract serves keys the committed allowlist does not "
                  f"name ({len(missing)}):", file=_sys.stderr)
            for m in missing[:40]:
                print("  " + m, file=_sys.stderr)
            return 1
        print(f"allowlist covers a fresh generation: {len(data['sections'])} "
              "sections, nothing unclassified")
        return 0
    target = Path(args.out) if args.out else tracked
    target.write_text(json.dumps(data, indent=1, sort_keys=True) + "\n")
    n = len(data["sections"])
    itemed = sum(1 for s in data["sections"].values() if s.get("items"))
    print(f"customer_allowlist.json: {n} sections, {itemed} with item-grain "
          f"keys, {len(EXCLUDED)} excluded keys")
    return 0


if __name__ == "__main__":
    sys.exit(main())
