#!/usr/bin/env python3
"""Transport a payload a producer has already authored, from a file to the connector.

    python3 scripts/submit_payload.py <run_id> <page> <payload.json> [--dry-run]

WHY THIS EXISTS, AND THE LINE IT DOES NOT CROSS
-----------------------------------------------
The skill tells a producing agent: "do not write a script that submits on your
behalf." That rule is right and it stays. It exists so that no payload is
mass-generated by code — every claim on a client's dashboard has to be
something the producer actually reasoned about and wrote.

At 700 cells that rule collided with the transport, and five producers hit the
collision on the same day. Chunked submit lifted the ceiling at the CONNECTOR
— `open_payload` / `append_payload_part` / `submit_page_payload` accept a
1.3 MB heatmap in parts — but `items` and `fields` are tool-call ARGUMENTS, so
every byte still has to pass through the model's own output. Measured by the
producers, not estimated:

    Northern Trust   1,360,972 B   685 cells   ~482 real parts, not 11
    Kitsap CU        2,068,509 B   706 cells
    Fisher           849,244 B     708 cells   ~430k tokens of context traffic
    Odlum Brown      490,765 B     708 cells   ~125k to read + ~125k to re-emit

So the two instructions were jointly unsatisfiable, and all five producers said
so and refused rather than quietly shrinking the served cell set — which is
exactly what they had been refused for the round before. The contradiction was
mine.

The resolution is a distinction the original rule never had to make, because
until now nothing was big enough to force it:

    AUTHORING may not be mechanised.  TRANSPORT may.

This script does not compose, summarise, template, reorder or infer anything.
It reads a file the producer wrote, splits it on section and item boundaries,
and hands the bytes to the connector. Every gate still runs server-side over
the assembled whole, exactly as it would have for an inline submit — the
connector cannot tell how the bytes arrived, and `submissions.transport`
records that it was chunked so a reader never has to guess.

If this script is ever extended to CHANGE a payload rather than carry it, that
is the rule being broken with extra steps.
"""
from __future__ import annotations

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# gcloud is not on the default PATH in every image this runs in, and without
# it `dma_connector` dies with a bare FileNotFoundError that reads like the
# connector is unreachable — a producer lost a round trip to it. Put the known
# locations on PATH before importing, so the failure that remains is a real one.
for _p in ("/root/google-cloud-sdk/bin", "/usr/lib/google-cloud-sdk/bin"):
    if os.path.isdir(_p) and _p not in os.environ.get("PATH", ""):
        os.environ["PATH"] = os.environ.get("PATH", "") + os.pathsep + _p

import dma_connector as C                                    # noqa: E402

# THE TRANSPORT CEILING, NOT THE MODEL CEILING.
#
# The connector publishes three numbers in get_page_contract(page)["transport"]
# and they answer different questions:
#
#   inline_max_bytes       131,072   what a MODEL can emit in one tool call.
#                                    Derived in transport.py from ~32k tokens
#                                    of output budget at ~4 bytes a token.
#   recommended_part_bytes 131,072   the same number, for the same reason.
#   max_part_bytes       1,048,576   what the CONNECTOR will accept in one
#                                    part. The only limit that binds a script.
#
# This script sized itself against the first one and left the third with zero
# readers anywhere in the repo. It has no token budget: it reads a file and
# posts JSON over HTTPS. Sizing a script's parts by what a model can type is
# the wrong constraint by an order of magnitude, and the cost is not
# theoretical — measured 2026-08-31 by a producer pushing a 1.5 MB heatmap:
#
#   at  96,000 bytes a part   ~53 parts, appended serially over minutes,
#                             every one a chance to be interrupted and a
#                             share of the rate-limit budget that returned
#                             429s when they were sent in parallel
#   at 900,000 bytes a part   2 parts
#
# So the ceiling is read FROM THE CONNECTOR at run time and only falls back to
# a literal when the contract cannot be reached. `PART_HEADROOM` leaves room
# for the JSON-RPC envelope around each part, which is not free.
PART_HEADROOM = 148_576          # ~14% of the 1 MiB ceiling
FALLBACK_MAX_PART_BYTES = 1_048_576
PART_BYTES = FALLBACK_MAX_PART_BYTES - PART_HEADROOM


def part_ceiling(page: str) -> int:
    """The connector's own max_part_bytes, less envelope headroom.

    Asked rather than assumed: if the connector lowers its ceiling this
    follows it down, and a script that kept posting 900 KB parts against a
    reduced limit would fail every part instead of one.
    """
    try:
        c = C.call("get_page_contract", page=page)
        n = int((c.get("transport") or {}).get("max_part_bytes") or 0)
    except Exception:
        n = 0
    if n <= 0:
        return PART_BYTES
    return max(n - PART_HEADROOM, n // 2)


def _size(obj) -> int:
    return len(json.dumps(obj, separators=(",", ":")))


def _plan(payload: dict, limit: int = PART_BYTES) -> list:
    """Split into parts on boundaries the payload already has.

    `limit` is the CONNECTOR's per-part ceiling less envelope headroom, not
    what a model can type — see `part_ceiling`.

    Sections small enough to travel whole do; a section whose item list is too
    large is sent as its envelope followed by runs of items. Nothing is
    reordered within a list, because order is meaning (rule 10) and a reordered
    ranking is a different claim.
    """
    parts: list = []
    small: dict = {}

    for name, section in payload.items():
        if _size({name: section}) <= limit:
            if _size(small) + _size({name: section}) > limit and small:
                parts.append({"path": "", "fields": dict(small)})
                small = {}
            small[name] = section
            continue

        # Too big whole. Find its one list-valued key — the item grain.
        lists = [k for k, v in section.items()
                 if isinstance(v, list) and _size(v) > limit // 2]
        if not isinstance(section, dict) or len(lists) != 1:
            raise SystemExit(
                f"section {name!r} is {_size(section)} bytes and has "
                f"{len(lists)} large list keys; this splitter handles exactly "
                f"one item list per section. Split it by hand rather than "
                f"letting a script guess which field is the grain.")
        key = lists[0]
        envelope = {k: v for k, v in section.items() if k != key}
        parts.append({"path": "", "fields": {name: {**envelope, key: []}}})

        run, run_bytes = [], 0
        for item in section[key]:
            b = _size(item)
            if run and run_bytes + b > limit:
                parts.append({"path": f"{name}.{key}", "items": run})
                run, run_bytes = [], 0
            run.append(item)
            run_bytes += b
        if run:
            parts.append({"path": f"{name}.{key}", "items": run})

    if small:
        parts.append({"path": "", "fields": small})
    return parts


def main() -> int:
    if len(sys.argv) < 4:
        print(__doc__.strip().splitlines()[2], file=sys.stderr)
        return 2
    run_id, page, path = sys.argv[1], sys.argv[2], sys.argv[3]
    dry = "--dry-run" in sys.argv

    def _opt(flag: str, default: str) -> str:
        return (sys.argv[sys.argv.index(flag) + 1]
                if flag in sys.argv and len(sys.argv) > sys.argv.index(flag) + 1
                else default)

    # Names the agent that AUTHORED the payload, not this script. The
    # connector already records `transport: chunked` on the submission, so how
    # the bytes travelled is not this field's job — and a producer_version
    # naming the transport would attribute the prose to a byte pusher.
    producer_version = _opt("--producer-version", "surface-producer@2026-08")
    provenance = _opt("--provenance", "producer")

    payload = json.load(open(path))
    total_bytes = _size(payload)
    # Ask the connector what it will accept before deciding how
    # finely to cut. The answer is usually 1 MiB, which is an
    # order of magnitude more than this script used to assume.
    limit = part_ceiling(page)
    parts = _plan(payload, limit)
    print(f"payload {total_bytes:,} bytes -> {len(parts)} part(s)")
    for i, p in enumerate(parts, 1):
        n = len(p.get("items") or ()) if "items" in p else None
        print(f"  part {i:3} {_size(p.get('items') or p.get('fields')):>8,} B "
              f"path={p['path']!r}" + (f" items={n}" if n is not None else ""))
    if dry:
        return 0

    up = C.call("open_payload", run_id=run_id, page=page)
    upload_id = up.get("upload_id") or up.get("id")
    if not upload_id:
        print(f"open_payload returned no upload id: {up}", file=sys.stderr)
        return 1
    print(f"upload {upload_id}")

    for i, p in enumerate(parts, 1):
        kw = {"upload_id": upload_id, "part": i, "parts_total": len(parts),
              "path": p["path"]}
        if "items" in p:
            kw["items"] = p["items"]
            kw["item_count"] = len(p["items"])
        else:
            kw["fields"] = p["fields"]
        r = C.call("append_payload_part", **kw)
        if r.get("ok") is False:
            print(f"part {i} refused: {r.get('error')} — {r.get('message')}",
                  file=sys.stderr)
            return 1
        print(f"  part {i}/{len(parts)} accepted")

    # `expect` declares the assembled length of every list this split fanned
    # out, so CG-17 catches a run of items lost at a valid element boundary —
    # the one truncation a JSON parse cannot see, and the one this splitter
    # could plausibly cause.
    expect = {}
    for p in parts:
        if "items" in p:
            expect[p["path"]] = expect.get(p["path"], 0) + len(p["items"])

    out = C.call("submit_page_payload", run_id=run_id, page=page,
                 upload_id=upload_id, provenance=provenance,
                 producer_version=producer_version, expect=expect)
    verdict = out.get("verdict") or {}
    reasons = verdict.get("reasons") or verdict.get("blocking") or []
    print(f"submission {out.get('submission_id')} status="
          f"{verdict.get('status') or out.get('status')} "
          f"blocking={len(reasons)}")
    # The first few only. A 700-cell page can return 700 reasons, and dumping
    # them all here buries the one that matters.
    for r in reasons[:12]:
        print("   ", json.dumps(r)[:300] if not isinstance(r, str) else r[:300])
    if len(reasons) > 12:
        print(f"    … {len(reasons) - 12} more; read the full verdict with "
              f"get_validation_verdict")
    return 0 if not reasons else 1


if __name__ == "__main__":
    raise SystemExit(main())
